-- VERIFICAÇÃO DA VERSÃO ATUAL DO BANCO DE DADOS
SET NOEXEC OFF

IF W3RC.FN_VERSAO_RC() <> '2023.3.0' BEGIN
	PRINT 'Versão atual: ' + W3RC.FN_VERSAO_RC()
	RAISERROR('ERRO: Estas alterações são incompatíveis com a versão atual.', 18, 1) WITH NOWAIT
	SET NOEXEC ON
END
GO

-- CICLO - Criação da coluna para armazenar o ano de referência
IF NOT EXISTS(
	SELECT * 
	FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_SCHEMA = 'W3RC' 
		AND TABLE_NAME = 'CICLO' 
		AND COLUMN_NAME = 'NUM_ANO_REFERENCIA')
BEGIN
	ALTER TABLE W3RC.CICLO ADD NUM_ANO_REFERENCIA	INT NULL
END
GO