CREATE FUNCTION W3IN.FN_CALCULAR_MEDIA_RELATIVA (@VLR_NOTA FLOAT, @MIN_NOTA FLOAT, @MAX_NOTA FLOAT, @MIN_RELATIVO FLOAT, @MAX_RELATIVO FLOAT)
	RETURNS DECIMAL(10, 2)
AS  
BEGIN
	DECLARE @VLR_RELATIVO FLOAT
	
	IF @MAX_NOTA = @MIN_NOTA
		SET @VLR_RELATIVO = @MAX_NOTA
	ELSE
		SET @VLR_RELATIVO = @MIN_RELATIVO + (((@VLR_NOTA - @MIN_NOTA) * (@MAX_RELATIVO - @MIN_RELATIVO)) / (@MAX_NOTA - @MIN_NOTA))

	RETURN CONVERT(DECIMAL(10, 2), @VLR_RELATIVO)
END