BEGIN TRAN

IF EXISTS (SELECT 1 FROM W3SI.IDIOMA WHERE COD_IDIOMA = 3)
BEGIN
	INSERT INTO W3IN.MENSAGEM_TMP (COD_IDIOMA, COD_MODULO, NOM_PAGINA, NOM_CONTROLE, NOM_PROPRIEDADE, NOM_CHAVE, DSC_MENSAGEM, IND_REVISADA) VALUES (3, 30, NULL, NULL, NULL, 'tituloTreinamento', 'Capacitación', 'N')
	INSERT INTO W3IN.MENSAGEM_TMP (COD_IDIOMA, COD_MODULO, NOM_PAGINA, NOM_CONTROLE, NOM_PROPRIEDADE, NOM_CHAVE, DSC_MENSAGEM, IND_REVISADA) VALUES (3, 30, NULL, NULL, NULL, 'subtituloTreinamento', 'Reinventa tu gestión de la formación utilizando experiencias digitales con acceso a indicadores.', 'N')
	INSERT INTO W3IN.MENSAGEM_TMP (COD_IDIOMA, COD_MODULO, NOM_PAGINA, NOM_CONTROLE, NOM_PROPRIEDADE, NOM_CHAVE, DSC_MENSAGEM, IND_REVISADA) VALUES (3, 30, NULL, NULL, NULL, 'mensagemPaginaTreinamento', '¿Ha sido un gran desafío capacitar a su equipo de manera atractiva y garantizar el compromiso? Cambia el proceso de aprendizaje de los empleados con metodologías de gamificación. <br>Una solución fácil de usar que permite centralizar contenidos, gestionar capacitaciones e incluso obtener indicadores para la toma de decisiones. <br>Si bien permite una mayor autonomía y visibilidad para los gerentes sobre el desarrollo de sus equipos, se traduce en ahorros de tiempo y recursos financieros al poner el conocimiento a disposición y generarlo en línea.', 'N')
	INSERT INTO W3IN.MENSAGEM_TMP (COD_IDIOMA, COD_MODULO, NOM_PAGINA, NOM_CONTROLE, NOM_PROPRIEDADE, NOM_CHAVE, DSC_MENSAGEM, IND_REVISADA) VALUES (3, 30, NULL, NULL, NULL, 'acessarSolucao', 'Acceder a la solución', 'N')
	INSERT INTO W3IN.MENSAGEM_TMP (COD_IDIOMA, COD_MODULO, NOM_PAGINA, NOM_CONTROLE, NOM_PROPRIEDADE, NOM_CHAVE, DSC_MENSAGEM, IND_REVISADA) VALUES (3, 30, NULL, NULL, NULL, 'tituloClave', 'Perfil de Comportamiento', 'N')
	INSERT INTO W3IN.MENSAGEM_TMP (COD_IDIOMA, COD_MODULO, NOM_PAGINA, NOM_CONTROLE, NOM_PROPRIEDADE, NOM_CHAVE, DSC_MENSAGEM, IND_REVISADA) VALUES (3, 30, NULL, NULL, NULL, 'subtituloClave', 'Accede al mapeo de perfiles de tus empleados y gana agilidad y calidad en la toma de decisiones.', 'N')
	INSERT INTO W3IN.MENSAGEM_TMP (COD_IDIOMA, COD_MODULO, NOM_PAGINA, NOM_CONTROLE, NOM_PROPRIEDADE, NOM_CHAVE, DSC_MENSAGEM, IND_REVISADA) VALUES (3, 30, NULL, NULL, NULL, 'mensagemPaginaClave', '¿Qué tal acelerar el alcance de los resultados de tu empresa entendiendo el potencial de tu equipo y dónde cada uno actúa con mejor desempeño? <br><br>Con la solución, es posible conocer en profundidad el perfil de comportamiento y las principales características de sus empleados, ya que ofrece datos importantes para identificar talentos y brechas a abordar. <br><br>Algunos beneficios son: comprender las aspiraciones de carrera y el propósito de vida de los empleados, mapear perfiles alineados con la cultura, estrategias y necesidades de la empresa y tomar mejores decisiones sobre contratación, desarrollo y sucesión.', 'N')
	-- MENSAGENS - (MANTENHA ESTE COMENTÁRIO COMO A ÚLTIMA LINHA)
END
COMMIT