--APAGA A TABELA W3IN.MENSAGEM_TMP CASO ELA EXISTA NO BANCO
IF EXISTS (SELECT 1
			FROM SYSOBJECTS
			WHERE  ID = OBJECT_ID('W3INS.MENSAGEM_TMP')
			AND TYPE IN ('U'))
	DROP TABLE W3IN.MENSAGEM_TMP
GO
