-- VERIFICAÇÃO DA VERSÃO ATUAL DO BANCO DE DADOS
SET NOEXEC OFF

IF W3IN.FN_VERSAO_IN() <> '2022.4.0' BEGIN
	PRINT 'Versão atual: ' + W3IN.FN_VERSAO_IN()
	RAISERROR('ERRO: Estas alterações são incompatíveis com a versão atual.', 18, 1) WITH NOWAIT
	SET NOEXEC ON
END
GO

DECLARE @COD_MODULO INT = 30

SELECT * INTO W3SI.TMP_PARAMETRO FROM W3SI.PARAMETRO WHERE 1 = 2;
-- Parametros Integração LMS
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
VALUES ('A', @COD_MODULO, 'S', 'IntegracaoTreinamento.EnvioDadosCorporativos', 'Indica se o envio de dados corporativos para o sistema Gen.te Aprende - Treinamento está habilitado.', 'FALSE', 'TRUE, Sim;FALSE, Não');
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
VALUES ('A', @COD_MODULO, 'S', 'IntegracaoTreinamento.UrlBaseApi', 'Indica a URL base para acesso as API''s do sistema Gen.te Aprende - Treinamento.', 'https://localhost/webapi/', NULL);
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
VALUES ('A', @COD_MODULO, 'S', 'IntegracaoTreinamento.TokenClientId', 'Valor do client_id fornecido pelo sistema Gen.te Aprende - Treinamento, para permitir a autenticaçao Oauth2 nas API''s do sistema.', 'client_id', NULL);
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
VALUES ('A', @COD_MODULO, 'S', 'IntegracaoTreinamento.TokenClientSecret', 'Valor do client_secret fornecido pelo sistema Gen.te Aprende - Treinamento, para permitir a autenticaçao Oauth2 nas API''s do sistema.', 'client_secret', NULL);
-- Parametros Integração Clave
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
VALUES ('A', @COD_MODULO, 'S', 'IntegracaoClave.EnvioDadosCorporativos', 'Indica se o envio de dados corporativos para o sistema da Clave está habilitado.', 'FALSE', 'TRUE, Sim;FALSE, Não');
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
VALUES ('A', @COD_MODULO, 'S', 'IntegracaoClave.UrlBase', 'Indica a URL base para acesso as APIs e ao login SSO, do sistema Fit de Comportamentos', 'https://localhost/webapi/', NULL);
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
VALUES ('A', @COD_MODULO, 'S', 'IntegracaoClave.Chave', 'Indica se o envio de dados corporativos para o sistema da Clave está habilitado.', 'client_secret', NULL);


MERGE W3SI.PARAMETRO AS TARGET
USING W3SI.TMP_PARAMETRO AS SOURCE 
ON (TARGET.COD_MODULO = 30 AND SOURCE.COD_MODULO = 30 AND TARGET.NOM_PARAMETRO = SOURCE.NOM_PARAMETRO)
WHEN MATCHED AND
	TARGET.IND_ESCOPO <> SOURCE.IND_ESCOPO
	OR TARGET.IND_TIPO_VALOR <> SOURCE.IND_TIPO_VALOR
	OR TARGET.NOM_PARAMETRO <> SOURCE.NOM_PARAMETRO
	OR TARGET.DSC_PARAMETRO <> SOURCE.DSC_PARAMETRO
	OR TARGET.DSC_OPCAO <> SOURCE.DSC_OPCAO
THEN 
	UPDATE SET
		TARGET.IND_ESCOPO = SOURCE.IND_ESCOPO,
		TARGET.IND_TIPO_VALOR = SOURCE.IND_TIPO_VALOR,
		TARGET.NOM_PARAMETRO = SOURCE.NOM_PARAMETRO,
		TARGET.DSC_PARAMETRO = SOURCE.DSC_PARAMETRO,
		TARGET.DSC_OPCAO = SOURCE.DSC_OPCAO
WHEN NOT MATCHED BY TARGET THEN
	INSERT (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
	VALUES (SOURCE.IND_ESCOPO, SOURCE.COD_MODULO, SOURCE.IND_TIPO_VALOR, SOURCE.NOM_PARAMETRO, SOURCE.DSC_PARAMETRO, SOURCE.VLR_PARAMETRO, SOURCE.DSC_OPCAO);

--VINCULA OS PARAMETROS PARA OS PERFIS
SELECT * INTO W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO FROM W3SI.PERFIL_ADMINISTRADOR_PARAMETRO WHERE 1 = 2

-- PARÂMETROS DO MÓDULO POR PERFIL ADMINISTRADOR 
DECLARE 
	@codPerfilAdminLG INT = 1,
	@codPerfilAdminGeral INT = 2,
	@codPerfilAdminAuxiliar INT = 3,
	@codPerfilConsultor INT = 4

--INSERE TODOS OS PARAMETROS PARA O ADMINISTRADOR LG
INSERT INTO W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO (COD_PERFIL_ADMINISTRADOR, COD_PARAMETRO)
	SELECT @codPerfilAdminLG, COD_PARAMETRO 
	FROM W3SI.PARAMETRO P
	WHERE COD_MODULO = @COD_MODULO

--INSERE TODOS OS PARAMETROS PARA O CONSULTOR
INSERT INTO W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO (COD_PERFIL_ADMINISTRADOR, COD_PARAMETRO)
	SELECT @codPerfilConsultor, COD_PARAMETRO 
	FROM W3SI.PARAMETRO P
	WHERE COD_MODULO = @COD_MODULO


--APLICA O MERGE
MERGE W3SI.PERFIL_ADMINISTRADOR_PARAMETRO AS TARGET
USING W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO AS SOURCE 
ON (TARGET.COD_PERFIL_ADMINISTRADOR = SOURCE.COD_PERFIL_ADMINISTRADOR AND TARGET.COD_PARAMETRO = SOURCE.COD_PARAMETRO)
WHEN NOT MATCHED BY TARGET AND SOURCE.COD_PARAMETRO IN (SELECT COD_PARAMETRO FROM W3SI.PARAMETRO WHERE COD_MODULO = @COD_MODULO)  THEN
	INSERT (COD_PERFIL_ADMINISTRADOR, COD_PARAMETRO) 
	VALUES (SOURCE.COD_PERFIL_ADMINISTRADOR, SOURCE.COD_PARAMETRO)
WHEN NOT MATCHED BY SOURCE AND TARGET.COD_PARAMETRO IN (SELECT COD_PARAMETRO FROM W3SI.PARAMETRO WHERE COD_MODULO = @COD_MODULO) THEN
DELETE;


DROP TABLE W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO


--APAGA OS PARAMETROS DESNECESSÁRIOS
DELETE FROM W3SI.PERFIL_ADMINISTRADOR_PARAMETRO
WHERE COD_PARAMETRO IN (
	SELECT COD_PARAMETRO
	FROM W3SI.PARAMETRO T
	WHERE NOT EXISTS (
		SELECT 1
		FROM W3SI.TMP_PARAMETRO S
		WHERE T.COD_MODULO = S.COD_MODULO AND T.NOM_PARAMETRO = S.NOM_PARAMETRO
	)
	AND T.COD_MODULO = @COD_MODULO
)
DELETE T
FROM W3SI.PARAMETRO T
WHERE NOT EXISTS (
	SELECT 1
	FROM W3SI.TMP_PARAMETRO S
	WHERE T.COD_MODULO = S.COD_MODULO AND T.NOM_PARAMETRO = S.NOM_PARAMETRO
)
AND T.COD_MODULO = @COD_MODULO


DROP TABLE W3SI.TMP_PARAMETRO

--Insert nos Submódulos para single sign on
IF NOT EXISTS (SELECT 1 FROM W3SI.SUBMODULO WHERE COD_MODULO = 30 AND COD_SUBMODULO = 3001) BEGIN
	INSERT INTO W3SI.SUBMODULO (COD_SUBMODULO, COD_MODULO, SGL_SUBMODULO, IND_TIPO_CONFIGURACAO, NOM_SUBMODULO, DSC_URL, IND_COMPATIBILIDADE, IND_PAINEL, IND_PAINEL_PRINCIPAL) 
	VALUES(3001, 30, 'TR', 'M','Gen.te Aprende – Treinamento', 'AreaUsuario/IntegracaoLms/Default.aspx','S', 'N', 'N')
END 
IF NOT EXISTS (SELECT 1 FROM W3SI.SUBMODULO WHERE COD_MODULO = 30 AND COD_SUBMODULO = 3002) BEGIN
	INSERT INTO W3SI.SUBMODULO (COD_SUBMODULO, COD_MODULO, SGL_SUBMODULO, IND_TIPO_CONFIGURACAO, NOM_SUBMODULO, DSC_URL, IND_COMPATIBILIDADE, IND_PAINEL, IND_PAINEL_PRINCIPAL) 
	VALUES(3002, 30, 'CL', 'M','Fit de Comportamentos Clave ', 'AreaUsuario/IntegracaoClave/Default.aspx','S', 'N', 'N')
END

--Altera o dsc_mensagem para a autenticacao integrada
UPDATE W3SI.PARAMETRO 
SET DSC_PARAMETRO = ' Chave utilizada para gerar o hash na integração com o sistema Gen.te Aprende – Treinamento.'
WHERE NOM_PARAMETRO = 'ChaveHashEguru'

UPDATE W3SI.PARAMETRO
SET DSC_PARAMETRO = 'URL utilizada na integração SSO com o sistema Gen.te Aprende – Treinamento.'
WHERE NOM_PARAMETRO = 'UrlSSOEguru'