<?xml version="1.0" encoding="utf-8"?>
<Mensagens>
	<Mensagem chave="atencao">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="erroAcessoParaNaoFuncionario">
		<pt-BR><![CDATA[Você não tem permissão de acesso ao sistema de Perfil Comportamental. Esse acesso é concedido somente á funcionários.]]></pt-BR>
		<en-US><![CDATA[You do not have permission to access the Behavioral Profile system. This access is granted to employees only.]]></en-US>
		<es-ES><![CDATA[No tiene permiso para acceder al sistema de perfil de comportamiento. Este acceso se concede únicamente a los empleados.]]></es-ES>
	</Mensagem>
	<Mensagem chave="erro_parametros">
		<pt-BR><![CDATA[Parâmetros inválidos.]]></pt-BR>
		<en-US><![CDATA[Invalid parameters.]]></en-US>
		<es-ES><![CDATA[parámetros inválidos.]]></es-ES>
	</Mensagem>
</Mensagens>