-- VERIFICAÇÃO DA VERSÃO ATUAL DO BANCO DE DADOS
SET NOEXEC OFF

IF W3IN.FN_VERSAO_IN() <> '2023.5.0' BEGIN
	PRINT 'Versão atual: ' + W3IN.FN_VERSAO_IN()
	RAISERROR('ERRO: Estas alterações são incompatíveis com a versão atual.', 18, 1) WITH NOWAIT
	SET NOEXEC ON
END
GO

IF EXISTS(SELECT OBJECT_ID FROM SYS.OBJECTS WHERE NAME = 'FN_VERSAO_IN' AND TYPE = 'FN')
	DROP FUNCTION  W3IN.FN_VERSAO_IN;
GO

CREATE FUNCTION W3IN.FN_VERSAO_IN()
RETURNS VARCHAR(20)
BEGIN
	RETURN '2023.6.0'
END