<?xml version="1.0" encoding="utf-8"?>
<Mensagens>
  <Mensagem chave="confirmacao">
    <pt-BR><![CDATA[Confirmação]]></pt-BR>
    <en-US><![CDATA[Confirm]]></en-US>
    <es-ES><![CDATA[Confirmación]]></es-ES>
  </Mensagem>
  <Mensagem chave="confirme_remover_customizacoes">
    <pt-BR><![CDATA[Confirma a EXCLUSÃO de TODAS as mensagens customizadas ?<br/>(esta operação não poderá ser desfeita)]]></pt-BR>
    <en-US><![CDATA[Confirm]]></en-US>
    <es-ES><![CDATA[¿Confirma la exclusión de todos los mensajes personalizados? <br/> (esta operación no se puede deshacer)]]></es-ES>
  </Mensagem>
  <Mensagem chave="RemoverTodasCustomizacoes">
    <pt-BR><![CDATA[TODAS as mensagens customizadas foram excluídas]]></pt-BR>
    <en-US><![CDATA[OK]]></en-US>
    <es-ES><![CDATA[Se borran todos los mensajes personalizados]]></es-ES>
  </Mensagem>
  <Mensagem chave="confirme_remover_customizacoes_selecionadas">
    <pt-BR><![CDATA[Confirma a EXCLUSÃO das customizações de {nSel} mensagem(s) selecionada(s) ?<br/>(esta operação não poderá ser desfeita)]]></pt-BR>
    <en-US><![CDATA[Confirm]]></en-US>
    <es-ES><![CDATA[¿Confirma la EXCLUSIÓN de personalización de {nSel} mensaje(s) seleccionado(s)? <br/> (Esta operación no se puede deshacer)]]></es-ES>
  </Mensagem>
  <Mensagem chave="RemoverCustomizacoesSelecionadas">
    <pt-BR><![CDATA[TODAS as mensagens customizadas SELECIONADAS foram excluídas]]></pt-BR>
    <en-US><![CDATA[OK]]></en-US>
    <es-ES><![CDATA[Se borran todos los mensajes personalizados SELECCIONADOS]]></es-ES>
  </Mensagem>
  <Mensagem chave="aviso">
    <pt-BR><![CDATA[Aviso]]></pt-BR>
    <en-US><![CDATA[Advice]]></en-US>
    <es-ES><![CDATA[Aviso]]></es-ES>
  </Mensagem>
  <Mensagem chave="selecione_registros_para_alteracao">
    <pt-BR><![CDATA[Nenhum registro foi selecionado.]]></pt-BR>
    <en-US><![CDATA[OK]]></en-US>
    <es-ES><![CDATA[Se seleccionaron ninguna ficha.]]></es-ES>
  </Mensagem>
</Mensagens>