<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="retornar">
		<pt-BR><![CDATA[Retornar upload]]></pt-BR>
		<en-US><![CDATA[Return upload]]></en-US>
		<es-ES><![CDATA[Volver upload]]></es-ES>
	</Mensagem>
	<Mensagem chave="importar">
		<pt-BR><![CDATA[Confirmar importação]]></pt-BR>
		<en-US><![CDATA[Confirm import]]></en-US>
		<es-ES><![CDATA[Confirmar la importación]]></es-ES>
	</Mensagem>
	<Mensagem chave="cancelar">
		<pt-BR><![CDATA[Cancelar]]></pt-BR>
		<en-US><![CDATA[Cancel]]></en-US>
		<es-ES><![CDATA[Cancelar]]></es-ES>
	</Mensagem>
	<Mensagem chave="importacao">
		<pt-BR><![CDATA[Importação]]></pt-BR>
		<en-US><![CDATA[Import]]></en-US>
		<es-ES><![CDATA[Importación]]></es-ES>
	</Mensagem>
	<Mensagem chave="erro">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="passo1Importacao">
		<pt-BR><![CDATA[Passo 1: Seleção da planilha]]></pt-BR>
		<en-US><![CDATA[Step 1: Selecting the spreadsheet]]></en-US>
		<es-ES><![CDATA[Paso 1: Selección de la planilla]]></es-ES>
	</Mensagem>
	<Mensagem chave="buscarPlanilha">
		<pt-BR><![CDATA[Busque a planilha excel a ser importada e clique no botão Processar]]></pt-BR>
		<en-US><![CDATA[Locate the excel sheet to be imported and click the Process button]]></en-US>
		<es-ES><![CDATA[Busque la planilla  Excel que desea importar y haga clic en el botón Procesar]]></es-ES>
	</Mensagem>
	<Mensagem chave="planilhaExcel">
		<pt-BR><![CDATA[Planilha excel:]]></pt-BR>
		<en-US><![CDATA[Excel spreadsheet:]]></en-US>
		<es-ES><![CDATA[Planilla Excel:]]></es-ES>
	</Mensagem>
	<Mensagem chave="msgOrientacoes">
		<pt-BR><![CDATA[Orientações]]></pt-BR>
		<en-US><![CDATA[Guidelines]]></en-US>
		<es-ES><![CDATA[Directrices]]></es-ES>
	</Mensagem>
	<Mensagem chave="msgColuna">
		<pt-BR><![CDATA[Coluna]]></pt-BR>
		<en-US><![CDATA[Column]]></en-US>
		<es-ES><![CDATA[columna]]></es-ES>
	</Mensagem>
	<Mensagem chave="msgEsperado">
		<pt-BR><![CDATA[Esperado]]></pt-BR>
		<en-US><![CDATA[Expected]]></en-US>
		<es-ES><![CDATA[esperado]]></es-ES>
	</Mensagem>
	<Mensagem chave="msgEncontrado">
		<pt-BR><![CDATA[Encontrado]]></pt-BR>
		<en-US><![CDATA[Found]]></en-US>
		<es-ES><![CDATA[fundar]]></es-ES>
	</Mensagem>
	<Mensagem chave="msgErro">
		<pt-BR><![CDATA[Erro]]></pt-BR>
		<en-US><![CDATA[Error]]></en-US>
		<es-ES><![CDATA[Error]]></es-ES>
	</Mensagem>
	<Mensagem chave="layoutPlanilhaInvalido">
		<pt-BR><![CDATA[Layout da planilha inválido]]></pt-BR>
		<en-US><![CDATA[Invalid worksheet layout]]></en-US>
		<es-ES><![CDATA[El diseño de la hoja de cálculo no es válido]]></es-ES>
	</Mensagem>
	<Mensagem chave="naoExistemPlanilhasValidas">
		<pt-BR><![CDATA[O Excel não contém nenhuma planilha válida]]></pt-BR>
		<en-US><![CDATA[Excel does not contain any valid spreadsheets]]></en-US>
		<es-ES><![CDATA[Excel no contiene ninguna planilla válida]]></es-ES>
	</Mensagem>
	<Mensagem chave="sim">
		<pt-BR><![CDATA[Sim]]></pt-BR>
		<en-US><![CDATA[Yes]]></en-US>
		<es-ES><![CDATA[Sí]]></es-ES>
	</Mensagem>
	<Mensagem chave="nao">
		<pt-BR><![CDATA[Não]]></pt-BR>
		<en-US><![CDATA[Not]]></en-US>
		<es-ES><![CDATA[No]]></es-ES>
	</Mensagem>
	<Mensagem chave="msgBotaoConfirmarAlteracao">
		<pt-BR><![CDATA[Clique no botão "Confirmar Importação" para efetivar a operação.]]></pt-BR>
		<en-US><![CDATA[Click the "Confirm Import" button to complete the operation.]]></en-US>
		<es-ES><![CDATA[Haga clic en el botón "Confirmar importación" para realizar la operación.]]></es-ES>
	</Mensagem>
	<Mensagem chave="planilhaContemErros">
		<pt-BR><![CDATA[A Planilha contém erros. Não é possível efetuar a importação.]]></pt-BR>
		<en-US><![CDATA[The spreadsheet contains errors. Can not import.]]></en-US>
		<es-ES><![CDATA[La planilla contiene errores. No se puede importar.]]></es-ES>
	</Mensagem>
	<Mensagem chave="planilhaSemAlteracoes">
		<pt-BR><![CDATA[A planilha não provoca Inclusões ou Alterações na base de dados]]></pt-BR>
		<en-US><![CDATA[Spreadsheet doe not provoke inclusions or changes in database]]></en-US>
		<es-ES><![CDATA[La planilla no provoca inclusiones o cambios en la base de datos]]></es-ES>
	</Mensagem>
	<Mensagem chave="uploadPlanilhaExcel">
		<pt-BR><![CDATA[Upload da planilha excel]]></pt-BR>
		<en-US><![CDATA[Excel spreadsheet upload]]></en-US>
		<es-ES><![CDATA[Subir la planilla Excel]]></es-ES>
	</Mensagem>
	<Mensagem chave="verificacaoConfirmacaoImportacao">
		<pt-BR><![CDATA[Verificação e confirmação da importação]]></pt-BR>
		<en-US><![CDATA[Import verification and confirmation]]></en-US>
		<es-ES><![CDATA[Verificación y confirmación de la importación]]></es-ES>
	</Mensagem>
	<Mensagem chave="inclusao_contratos">
		<pt-BR><![CDATA[Inclusão de contratos]]></pt-BR>
		<en-US><![CDATA[Inclusion of contracts]]></en-US>
		<es-ES><![CDATA[Inclusión de contratos]]></es-ES>
	</Mensagem>
	<Mensagem chave="plano">
		<pt-BR><![CDATA[Plano]]></pt-BR>
		<en-US><![CDATA[Plan]]></en-US>
		<es-ES><![CDATA[Plan]]></es-ES>
	</Mensagem>
	<Mensagem chave="id">
		<pt-BR><![CDATA[Id]]></pt-BR>
		<en-US><![CDATA[Id]]></en-US>
		<es-ES><![CDATA[Id]]></es-ES>
	</Mensagem>
	<Mensagem chave="id_nao_encontrado">
		<pt-BR><![CDATA[ID do colaborador não encontrado ou o mesmo se encontra inativo]]></pt-BR>
		<en-US><![CDATA[Employee ID not found or inactive]]></en-US>
		<es-ES><![CDATA[ID del empleado no encontrado o el mismo se encuentra inactivo]]></es-ES>
	</Mensagem>
	<Mensagem chave="id_duplicado_lista">
		<pt-BR><![CDATA[O ID está duplicado na lista]]></pt-BR>
		<en-US><![CDATA[ID is duplicate in list]]></en-US>
		<es-ES><![CDATA[ID es duplicado en la lista]]></es-ES>
	</Mensagem>
	<Mensagem chave="ciclo_nao_permite_multiplos_contratos">
		<pt-BR><![CDATA[O ciclo não permite múltiplos contratos e o colaborador já participa de outro plano]]></pt-BR>
		<en-US><![CDATA[The cycle does not allow multiple contracts and the employee already participates in another plan]]></en-US>
		<es-ES><![CDATA[El ciclo no permite múltiples contratos y el colaborador ya participa de otro plano]]></es-ES>
	</Mensagem>
	<Mensagem chave="colaborador_no_plano">
		<pt-BR><![CDATA[Colaborador já está participando do plano]]></pt-BR>
		<en-US><![CDATA[Employee is already participating in the plan]]></en-US>
		<es-ES><![CDATA[El empleado ya está participando en el plan]]></es-ES>
	</Mensagem>
	<Mensagem chave="permissao_para_importacao_do_colaborador">
		<pt-BR><![CDATA[Você não tem permissões para importar este colaborador]]></pt-BR>
		<en-US><![CDATA[You do not have permissions to import this employee]]></en-US>
		<es-ES><![CDATA[No tiene permisos para importar este empleado]]></es-ES>
	</Mensagem>
	<Mensagem chave="colaborador_nao_elegivel_publico_alvo">
		<pt-BR><![CDATA[O colaborador não é elegível ao público-alvo configurado para o plano]]></pt-BR>
		<en-US><![CDATA[The employee is not eligible to the target audience set up for the plan]]></en-US>
		<es-ES><![CDATA[El empleado no es elegible para la audiencia objetivo configurada para el plano]]></es-ES>
	</Mensagem>
	<Mensagem chave="contrato_grupo_inconsistente">
		<pt-BR><![CDATA[Existem contratos de grupos com inconsistências, dessa forma o plano será inativado. Você confirma a importação?]]></pt-BR>
		<en-US><![CDATA[There are group contracts with inconsistencies, so the plan will be inactivated. Do you confirm the import?]]></en-US>
		<es-ES><![CDATA[Hay contratos de grupos con inconsistencias, por lo que el plan se desactivará. ¿Confirmas la importación?]]></es-ES>
	</Mensagem>
	<Mensagem chave="pelo_menos_um_contrato_grupo_inconsistente">
		<pt-BR><![CDATA[Existe pelo menos um plano com contratos de grupos com inconsistências, dessa forma o plano será inativado. Você confirma a importação?]]></pt-BR>
		<en-US><![CDATA[There is at least one plan with group contracts with inconsistencies, so the plan will be inactivated. Do you confirm the import?]]></en-US>
		<es-ES><![CDATA[Hay al menos un plan con contratos de grupos con inconsistencias, por lo que el plan se desactivará. ¿Confirmas la importación?]]></es-ES>
	</Mensagem>
	<Mensagem chave="plano_nao_encontrado">
		<pt-BR><![CDATA[Plano não encontrado]]></pt-BR>
		<en-US><![CDATA[Plan not found]]></en-US>
		<es-ES><![CDATA[Plan no encontrado]]></es-ES>
	</Mensagem>
	
</Mensagens>
