<?xml version="1.0" encoding="utf-8"?>
<Mensagens>
  <Mensagem chave="idiomas">
    <pt-BR><![CDATA[Idiomas]]></pt-BR>
    <en-US><![CDATA[Language]]></en-US>
    <es-ES><![CDATA[Idiomas]]></es-ES>
  </Mensagem>
  <Mensagem chave="LocalizarIdioma">
    <pt-BR><![CDATA[Localizar nos idiomas]]></pt-BR>
    <en-US><![CDATA[Locate in languages]]></en-US>
    <es-ES><![CDATA[Encuentra las lenguas]]></es-ES>
  </Mensagem>
  <Mensagem chave="opcoes">
    <pt-BR><![CDATA[Opções]]></pt-BR>
    <en-US><![CDATA[Options]]></en-US>
    <es-ES><![CDATA[Opciones]]></es-ES>
  </Mensagem>
  <Mensagem chave="capitalizado">
    <pt-BR><![CDATA[Buscar e trocar PALAVRAs, ignorando maiúsculas, minúsculas e acentos]]></pt-BR>
    <en-US><![CDATA[Search WORDS, case insensitive, acents insensitive]]></en-US>
    <es-ES><![CDATA[Buscar y intercambiar PALABRAS, ignorando mayúsculas, minúsculas y acentos]]></es-ES>
  </Mensagem>
  <Mensagem chave="case_insensitive">
    <pt-BR><![CDATA[Buscar e trocar EXPRESSÕES, ignorando maiúsculas, minúsculas e acentos]]></pt-BR>
    <en-US><![CDATA[Search EXPRESSIONS, case insensitive, acents insensitive]]></en-US>
    <es-ES><![CDATA[Buscar y intercambiar EXPRESIONES, ignorando mayúsculas, minúsculas y acentos]]></es-ES>
  </Mensagem>
  <Mensagem chave="case_sensitive">
    <pt-BR><![CDATA[Buscar e trocar EXPRESSÕES, ignorando maiúsculas, minúsculas e acentos]]></pt-BR>
    <en-US><![CDATA[Search EXPRESSIONS, case insensitive, acents insensitive]]></en-US>
    <es-ES><![CDATA[Buscar y intercambiar EXPRESIONES, ignorando mayúsculas, minúsculas y acentos]]></es-ES>
  </Mensagem>
  <Mensagem chave="substituir">
    <pt-BR><![CDATA[Substituir]]></pt-BR>
    <en-US><![CDATA[Replace]]></en-US>
    <es-ES><![CDATA[Reemplazar]]></es-ES>
  </Mensagem>
  <Mensagem chave="Localizar">
    <pt-BR><![CDATA[Localizar]]></pt-BR>
    <en-US><![CDATA[Find]]></en-US>
    <es-ES><![CDATA[Localizar]]></es-ES>
  </Mensagem>
  <Mensagem chave="SubstituirPor">
    <pt-BR><![CDATA[Substituir por]]></pt-BR>
    <en-US><![CDATA[Replace by]]></en-US>
    <es-ES><![CDATA[Reemplazar]]></es-ES>
  </Mensagem>
  <Mensagem chave="retorno_encontradas">
    <pt-BR><![CDATA[Encontradas {nEncontradas} ocorrências em {nItens} mensagens]]></pt-BR>
    <en-US><![CDATA[Found {nEncontradas} ocurrences in {nItens} messages]]></en-US>
    <es-ES><![CDATA[Encontradas {nEncontradas} ocurrencias en {nItens} mensajes]]></es-ES>
  </Mensagem>
</Mensagens>