-- VERIFICAÇÃO DA VERSÃO ATUAL DO BANCO DE DADOS
SET NOEXEC OFF

IF W3IN.FN_VERSAO_IN() <> '2021.3.0' BEGIN
	PRINT 'Versão atual: ' + W3IN.FN_VERSAO_IN()
	RAISERROR('ERRO: Estas alterações são incompatíveis com a versão atual.', 18, 1) WITH NOWAIT
	SET NOEXEC ON
END
GO

UPDATE W3IN.TIPO_INTEGRACAO
SET NOM_TIPO_INTEGRACAO = 'Autoatendimento'
WHERE COD_TIPO_INTEGRACAO = 1
GO