-- VERIFICAÇÃO DA VERSÃO ATUAL DO BANCO DE DADOS
SET NOEXEC OFF

IF W3IN.FN_VERSAO_IN() <> '2023.4.0' BEGIN
	PRINT 'Versão atual: ' + W3IN.FN_VERSAO_IN()
	RAISERROR('ERRO: Estas alterações são incompatíveis com a versão atual.', 18, 1) WITH NOWAIT
	SET NOEXEC ON
END
GO

IF NOT EXISTS (
	SELECT 1 
	FROM W3IN.TIPO_INTEGRACAO 
	WHERE COD_TIPO_INTEGRACAO = 2)
BEGIN
INSERT INTO W3IN.TIPO_INTEGRACAO (COD_TIPO_INTEGRACAO, NOM_TIPO_INTEGRACAO) VALUES (2 , 'Autenticação Integrada')
END
IF NOT EXISTS (
	SELECT 1 
	FROM W3IN.CONFIGURACAO_INTEGRACAO 
	WHERE ID_CONFIGURACAO_INTEGRACAO = 'UrlBase' AND COD_TIPO_INTEGRACAO = 2)
BEGIN
INSERT INTO W3IN.CONFIGURACAO_INTEGRACAO (COD_TIPO_INTEGRACAO, ID_CONFIGURACAO_INTEGRACAO, VLR_CONFIGURACAO_INTEGRACAO, DAT_ALTERACAO) VALUES (2, 'UrlBase', 'https://login.lg.com.br', getdate())
END
IF NOT EXISTS (
	SELECT 1 
	FROM W3IN.CONFIGURACAO_INTEGRACAO 
	WHERE ID_CONFIGURACAO_INTEGRACAO = 'ChavePublica' AND COD_TIPO_INTEGRACAO = 2)
BEGIN
INSERT INTO W3IN.CONFIGURACAO_INTEGRACAO (COD_TIPO_INTEGRACAO, ID_CONFIGURACAO_INTEGRACAO, VLR_CONFIGURACAO_INTEGRACAO, DAT_ALTERACAO) VALUES (2, 'ChavePublica', 'ec0e957c-c0d7-4284-b557-88ba6610ea1d', getdate())
END
IF NOT EXISTS (
	SELECT 1 
	FROM W3IN.CONFIGURACAO_INTEGRACAO 
	WHERE ID_CONFIGURACAO_INTEGRACAO = 'ChavePrivada' AND COD_TIPO_INTEGRACAO = 2)
BEGIN
INSERT INTO W3IN.CONFIGURACAO_INTEGRACAO (COD_TIPO_INTEGRACAO, ID_CONFIGURACAO_INTEGRACAO, VLR_CONFIGURACAO_INTEGRACAO, DAT_ALTERACAO) VALUES (2, 'ChavePrivada', '9bc85c98-9bae-4446-b1d8-4004ebeab5a4', getdate())
END