<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="atencao">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
  <Mensagem chave="erro">
    <pt-BR><![CDATA[Atenção!]]></pt-BR>
    <en-US><![CDATA[Attention!]]></en-US>
    <es-ES><![CDATA[Atención!]]></es-ES>
  </Mensagem>
  <Mensagem chave="aguarde_carregando">
    <pt-BR><![CDATA[Aguarde carregando...]]></pt-BR>
    <en-US><![CDATA[Loading...Please Wait...]]></en-US>
    <es-ES><![CDATA[Espere…Cargando…]]></es-ES>
  </Mensagem>
	<Mensagem chave="campo_preenchimento_obrigatorio">
		<pt-BR><![CDATA[Campo de preenchimento obrigatório]]></pt-BR>
		<en-US><![CDATA[Mandatory completion field ]]></en-US>
		<es-ES><![CDATA[Campo de cumplimentación obligatoria]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_integracao_gente_aprende">
		<pt-BR><![CDATA[Chave utilizada para gerar o hash na integração com o sistema Gen.te Aprende – Treinamento]]></pt-BR>
		<en-US><![CDATA[Key used to generate the hash in the integration with the Gen.te Aprende – Training system]]></en-US>
		<es-ES><![CDATA[Clave utilizada para generar el hash en la integración con el sistema Gen.te Aprende – Training]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_integracao_sso_eguru">
		<pt-BR><![CDATA[URL utilizada na integração SSO com o sistema Gen.te Aprende – Treinamento]]></pt-BR>
		<en-US><![CDATA[URL utilizada en la integración SSO con el sistema Gen.te Aprende – Training]]></en-US>
		<es-ES><![CDATA[URL used in the SSO integration with the Gen.te Aprende – Training system]]></es-ES>
	</Mensagem>
  <Mensagem chave="dados_salvos_com_sucesso">
    <pt-BR><![CDATA[Dados salvos com sucesso!]]></pt-BR>
    <en-US><![CDATA[Data saved successfully!]]></en-US>
    <es-ES><![CDATA[¡Datos guardados con éxito!]]></es-ES>
  </Mensagem>
  <Mensagem chave="url_invalida">
    <pt-BR><![CDATA[Informe um endereço válido]]></pt-BR>
    <en-US><![CDATA[Please provide a valid address]]></en-US>
    <es-ES><![CDATA[Proporcione una dirección válida]]></es-ES>
  </Mensagem>
</Mensagens>
