<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="atencao">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="erro">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="alerta_simplifica">
		<pt-BR><![CDATA[Esta integração deverá ser habilitada somente para clientes da oferta SIMPLIFICA]]></pt-BR>
		<en-US><![CDATA[This integration must be enabled only for customers of the SIMPLIFICA offer]]></en-US>
		<es-ES><![CDATA[Esta integración debe estar habilitada solo para clientes de la oferta SIMPLIFICA]]></es-ES>
	</Mensagem>
	<Mensagem chave="aguarde_carregando">
		<pt-BR><![CDATA[Aguarde carregando...]]></pt-BR>
		<en-US><![CDATA[Loading...Please Wait...]]></en-US>
		<es-ES><![CDATA[Espere…Cargando…]]></es-ES>
	</Mensagem>
	<Mensagem chave="campo_preenchimento_obrigatorio">
		<pt-BR><![CDATA[Campo de preenchimento obrigatório]]></pt-BR>
		<en-US><![CDATA[Mandatory completion field ]]></en-US>
		<es-ES><![CDATA[Campo de cumplimentación obligatoria]]></es-ES>
	</Mensagem>

	<Mensagem chave="envio_dados_corporativos">
		<pt-BR><![CDATA[Indica se o envio de dados corporativos para o sistema Gen.te Aprende - Treinamento está habilitado]]></pt-BR>
		<en-US><![CDATA[Indicates whether sending corporate data to the Gen.te Aprende - Training system is enabled]]></en-US>
		<es-ES><![CDATA[Indica si está habilitado el envío de datos corporativos al sistema Gen.te Aprende - Capacitación]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_base_api">
		<pt-BR><![CDATA[Indica a URL base para acesso as API's do sistema Gen.te Aprende - Treinamento]]></pt-BR>
		<en-US><![CDATA[Indicates the base URL for accessing the API's of the Gen.te Aprende - Training system]]></en-US>
		<es-ES><![CDATA[Indica la URL base para acceder a las API's del Gen.te Aprende - Sistema de entrenamiento]]></es-ES>
	</Mensagem>
	<Mensagem chave="token_client_id">
		<pt-BR><![CDATA[Valor do client_id fornecido pelo sistema Gen.te Aprende - Treinamento, para permitir a autenticação Oauth2 nas API's do sistema]]></pt-BR>
		<en-US><![CDATA[Client_id value provided by the Gen.te Aprende - Training system, to allow Oauth2 authentication in the system's APIs]]></en-US>
		<es-ES><![CDATA[Valor de Client_id proporcionado por el sistema Gen.te Aprendi - Training, para permitir la autenticación Oauth2 en las API del sistema]]></es-ES>
	</Mensagem>
	<Mensagem chave="token_client_secret">
		<pt-BR><![CDATA[Valor do client_secret fornecido pelo sistema Gen.te Aprende - Treinamento, para permitir a autenticação Oauth2 nas API's do sistema]]></pt-BR>
		<en-US><![CDATA[Client_secret value provided by the Gen.te Aprende - Training system, to allow Oauth2 authentication in the system's APIs]]></en-US>
		<es-ES><![CDATA[Valor de Client_secret proporcionado por el sistema Gen.te Aprende - Training, para permitir la autenticación Oauth2 en las API del sistema]]></es-ES>
	</Mensagem>
	<Mensagem chave="sim">
		<pt-BR><![CDATA[Sim]]></pt-BR>
		<en-US><![CDATA[Yes]]></en-US>
		<es-ES><![CDATA[Si]]></es-ES>
	</Mensagem>
	<Mensagem chave="nao">
		<pt-BR><![CDATA[Não]]></pt-BR>
		<en-US><![CDATA[Not]]></en-US>
		<es-ES><![CDATA[No]]></es-ES>
	</Mensagem>

	<Mensagem chave="dados_salvos_com_sucesso">
		<pt-BR><![CDATA[Dados salvos com sucesso!]]></pt-BR>
		<en-US><![CDATA[Data saved successfully!]]></en-US>
		<es-ES><![CDATA[¡Datos guardados con éxito!]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_invalida">
		<pt-BR><![CDATA[Informe um endereço válido]]></pt-BR>
		<en-US><![CDATA[Please provide a valid address]]></en-US>
		<es-ES><![CDATA[Proporcione una dirección válida]]></es-ES>
	</Mensagem>
</Mensagens>
