<?xml version="1.0" encoding="utf-8"?>
<Mensagens>
	<Mensagem chave="atencao">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="erroAcessoFeedback">
		<pt-BR><![CDATA[Não foi possível acessar o sistema de Feeback. Por favor entre em contato com o administrador do Sistema.]]></pt-BR>
		<en-US><![CDATA[Unable to access the Feedback system. Please contact your System administrator.]]></en-US>
		<es-ES><![CDATA[No se puede acceder al sistema de Feeback. Por favor, póngase en contacto con el administrador del sistema.]]></es-ES>
	</Mensagem>
	<Mensagem chave="erroColaboradorID">
		<pt-BR><![CDATA[O colaborador alvo do Feedback não possui um IDPessoa cadastrado. Por favor entre em contato com o administrador do Sistema.]]></pt-BR>
		<en-US><![CDATA[The collaborator targeted by the Feedback does not have a registered PersonID. Please contact your System administrator.]]></en-US>
		<es-ES><![CDATA[El colaborador al que se dirigen los comentarios no tiene un PersonID registrado. Por favor, póngase en contacto con el administrador del sistema.]]></es-ES>
	</Mensagem>
	<Mensagem chave="acessoFeedbackUsuario">
		<pt-BR><![CDATA[Você não possui acesso ao sistema de Feedback. Por favor entre em contato com o administrador do Sistema.]]></pt-BR>
		<en-US><![CDATA[You do not have access to the Feedback system. Please contact your System administrator.]]></en-US>
		<es-ES><![CDATA[No tienes acceso al sistema de Feedback. Por favor, póngase en contacto con el administrador del sistema.]]></es-ES>
	</Mensagem>
</Mensagens>