<?xml version="1.0" encoding="utf-8"?>
<Mensagens>
	<Mensagem chave="mensagem_exclusao_parametro">
		<pt-BR><![CDATA[Não é possível excluir parâmetros.]]></pt-BR>
		<en-US><![CDATA[It is not possible to exclude parameters.]]></en-US>
		<es-ES><![CDATA[No es posible excluir parámetros]]></es-ES>
	</Mensagem>
	<Mensagem chave="titulo_inclusao">
		<pt-BR><![CDATA[Incluir Parâmetro]]></pt-BR>
		<en-US><![CDATA[Include Parameter]]></en-US>
		<es-ES><![CDATA[Incluir parámetro]]></es-ES>
	</Mensagem>
	<Mensagem chave="titulo_edicao">
		<pt-BR><![CDATA[Editar Parâmetro]]></pt-BR>
		<en-US><![CDATA[Edit Parameter]]></en-US>
		<es-ES><![CDATA[Editar parámetro]]></es-ES>
	</Mensagem>
	<Mensagem chave="aplicar_parametros">
		<pt-BR><![CDATA[Aplicar Parâmetros]]></pt-BR>
		<en-US><![CDATA[Apply Parameters]]></en-US>
		<es-ES><![CDATA[Aplicar parámetros]]></es-ES>
	</Mensagem>
	<Mensagem chave="parametros_aplicados_com_sucesso">
		<pt-BR><![CDATA[Parâmetros aplicados com sucesso.]]></pt-BR>
		<en-US><![CDATA[Parameters successfully applied.]]></en-US>
		<es-ES><![CDATA[Parámetros aplicados correctamente.]]></es-ES>
	</Mensagem>
	<Mensagem chave="incluir">
		<pt-BR><![CDATA[Incluir]]></pt-BR>
		<en-US><![CDATA[Insert]]></en-US>
		<es-ES><![CDATA[Incluir]]></es-ES>
	</Mensagem>
	<Mensagem chave="editar">
		<pt-BR><![CDATA[Editar]]></pt-BR>
		<en-US><![CDATA[Edit]]></en-US>
		<es-ES><![CDATA[Editar]]></es-ES>
	</Mensagem>
	<Mensagem chave="clonar">
		<pt-BR><![CDATA[Clonar]]></pt-BR>
		<en-US><![CDATA[Clone]]></en-US>
		<es-ES><![CDATA[Clonar]]></es-ES>
	</Mensagem>
	<Mensagem chave="excluir">
		<pt-BR><![CDATA[Excluir]]></pt-BR>
		<en-US><![CDATA[Delete]]></en-US>
		<es-ES><![CDATA[Eliminar]]></es-ES>
	</Mensagem>
	<Mensagem chave="moverbaixo">
		<pt-BR><![CDATA[Mover para baixo]]></pt-BR>
		<en-US><![CDATA[Move down]]></en-US>
		<es-ES><![CDATA[Mover hacia abajo]]></es-ES>
	</Mensagem>
	<Mensagem chave="movercima">
		<pt-BR><![CDATA[Mover para cima]]></pt-BR>
		<en-US><![CDATA[Move up]]></en-US>
		<es-ES><![CDATA[Mover hacia arriba]]></es-ES>
	</Mensagem>
	<Mensagem chave="atualizar">
		<pt-BR><![CDATA[Atualizar]]></pt-BR>
		<en-US><![CDATA[Refresh]]></en-US>
		<es-ES><![CDATA[Actualizar]]></es-ES>
	</Mensagem>
	<Mensagem chave="trocarseletor">
		<pt-BR><![CDATA[Seletor]]></pt-BR>
		<en-US><![CDATA[Selector]]></en-US>
		<es-ES><![CDATA[Selector]]></es-ES>
	</Mensagem>
	<Mensagem chave="selradio">
		<pt-BR><![CDATA[RadioBox]]></pt-BR>
		<en-US><![CDATA[RadioBox]]></en-US>
		<es-ES><![CDATA[RadioBox]]></es-ES>
	</Mensagem>
	<Mensagem chave="selcheck">
		<pt-BR><![CDATA[CheckBox]]></pt-BR>
		<en-US><![CDATA[CheckBox]]></en-US>
		<es-ES><![CDATA[CheckBox]]></es-ES>
	</Mensagem>
	<Mensagem chave="filtros">
		<pt-BR><![CDATA[Filtros]]></pt-BR>
		<en-US><![CDATA[Filters]]></en-US>
		<es-ES><![CDATA[Filtros]]></es-ES>
	</Mensagem>
	<Mensagem chave="filtrolimpar">
		<pt-BR><![CDATA[Limpar todos os filtros]]></pt-BR>
		<en-US><![CDATA[Clean all filters]]></en-US>
		<es-ES><![CDATA[Limpiar todos los filtros]]></es-ES>
	</Mensagem>
	<Mensagem chave="filtroadicional">
		<pt-BR><![CDATA[Filtros adicionais]]></pt-BR>
		<en-US><![CDATA[Advanced filters]]></en-US>
		<es-ES><![CDATA[Filtros adicionales]]></es-ES>
	</Mensagem>
	<Mensagem chave="expimp">
		<pt-BR><![CDATA[Exportar / Importar]]></pt-BR>
		<en-US><![CDATA[Export / Import]]></en-US>
		<es-ES><![CDATA[Exportar / Importar]]></es-ES>
	</Mensagem>
	<Mensagem chave="exportgrid">
		<pt-BR><![CDATA[Exportar Grid]]></pt-BR>
		<en-US><![CDATA[Export Grid]]></en-US>
		<es-ES><![CDATA[Exportar rejilla]]></es-ES>
	</Mensagem>
	<Mensagem chave="exportar">
		<pt-BR><![CDATA[Exportar Dados]]></pt-BR>
		<en-US><![CDATA[Export Data]]></en-US>
		<es-ES><![CDATA[Exportar datos]]></es-ES>
	</Mensagem>
	<Mensagem chave="importar">
		<pt-BR><![CDATA[Importar Dados]]></pt-BR>
		<en-US><![CDATA[Import Data]]></en-US>
		<es-ES><![CDATA[Importar datos]]></es-ES>
	</Mensagem>
	<Mensagem chave="aplicar">
		<pt-BR><![CDATA[Aplicar]]></pt-BR>
		<en-US><![CDATA[Apply]]></en-US>
		<es-ES><![CDATA[Aplicar]]></es-ES>
	</Mensagem>
	<Mensagem chave="NomParametro">
		<pt-BR><![CDATA[Parâmetro]]></pt-BR>
		<en-US><![CDATA[Parameter]]></en-US>
		<es-ES><![CDATA[Parámetros]]></es-ES>
	</Mensagem>
	<Mensagem chave="DscParametro">
		<pt-BR><![CDATA[Descrição]]></pt-BR>
		<en-US><![CDATA[Description]]></en-US>
		<es-ES><![CDATA[Descripción]]></es-ES>
	</Mensagem>
	<Mensagem chave="VlrParametro">
		<pt-BR><![CDATA[Valor]]></pt-BR>
		<en-US><![CDATA[Value]]></en-US>
		<es-ES><![CDATA[Valor]]></es-ES>
	</Mensagem>
</Mensagens>