CREATE TABLE [W3IN].[CONFIGURACAO_INTEGRACAO]
(
	[COD_CONFIGURACAO_INTEGRACAO] INT IDENTITY (1, 1) NOT NULL, 
    [COD_TIPO_INTEGRACAO] INT NOT NULL, 
    [ID_CONFIGURACAO_INTEGRACAO] VARCHAR(100) NOT NULL, 
    [VLR_CONFIGURACAO_INTEGRACAO] VARCHAR(4000) NOT NULL, 
    [DAT_ALTERACAO] DATETIME NOT NULL,

    CONSTRAINT PK_CONFINTE PRIMARY KEY CLUSTERED ([COD_CONFIGURACAO_INTEGRACAO] ASC),
    CONSTRAINT FK_TIPOINTE_CONFINTE_01 FOREIGN KEY ([COD_TIPO_INTEGRACAO]) REFERENCES [W3IN].[TIPO_INTEGRACAO] ([COD_TIPO_INTEGRACAO])
)
