CREATE TABLE [W3IN].[CONFIGURACAO_API] (
		[COD_API]						INT NOT NULL,
    [COD_MODULO]					INT NOT NULL,
		[COD_REGRA_VER_AVALIACAO]		INT NULL,
		[IND_TIPO_VALIDACAO_AC]			CHAR(1) NULL,
		[IND_NOTA_ORIGEM_AC]			CHAR(1) NULL,
		[IND_NOTA_ORIGEM_RC]			CHAR(1) NULL,
		[IND_NOTA_ORIGEM_ME]			CHAR(1) NULL,		
		[IND_EXPIRACAO_RESULTADOS]		CHAR(1) NOT NULL
			CONSTRAINT [DF_CONFIAPI_IND_EXPIRACAO_RESULTADOS]
				DEFAULT 'N'
            CONSTRAINT [CK_CONFIAPI_IND_EXPIRACAO_RESULTADOS]
                CHECK ([IND_EXPIRACAO_RESULTADOS] IN ('S', 'N')),
		[IND_ANO_REFERENCIA]			CHAR(1) NOT NULL
			CONSTRAINT [DF_CONFIAPI_IND_ANO_REFERENCIA]
				DEFAULT 'N'
            CONSTRAINT [CK_CONFIAPI_IND_ANO_REFERENCIA]
                CHECK ([IND_ANO_REFERENCIA] IN ('S', 'N')),
		[IND_RANGE_ESPECIFICO]			CHAR(1) NOT NULL
			CONSTRAINT [DF_CONFIAPI_IND_RANGE_ESPECIFICO]
				DEFAULT 'N'
            CONSTRAINT [CK_CONFIAPI_IND_RANGE_ESPECIFICO]
                CHECK ([IND_RANGE_ESPECIFICO] IN ('S', 'N')),
		[QTD_DIAS_EXPIRACAO]			INT NULL,
		[NUM_ANO_REFERENCIA]			INT NULL,
		[VLR_MINIMO_RANGE]				FLOAT NULL,
		[VLR_MAXIMO_RANGE]				FLOAT NULL,
        CONSTRAINT [PK_CONFIAPI] PRIMARY KEY CLUSTERED ([COD_API] ASC, [COD_MODULO] ASC),
		CONSTRAINT [FK_CONFIAPI_MODULO] FOREIGN KEY ([COD_MODULO]) 
			REFERENCES [W3SI].[MODULO] ([COD_MODULO]) ON DELETE CASCADE,
		CONSTRAINT [CK_CONFIAPI_IND_TIPO_VALIDACAO_AC] CHECK ([IND_TIPO_VALIDACAO_AC] IN ('C', 'V', 'R')),
		CONSTRAINT [CK_CONFIAPI_IND_EIXO_ORIGEM_AC] CHECK ([IND_NOTA_ORIGEM_AC] IN ('X', 'Y', 'Z')),
		CONSTRAINT [CK_CONFIAPI_IND_EIXO_ORIGEM_RC] CHECK ([IND_NOTA_ORIGEM_RC] IN ('X', 'Y')),
		CONSTRAINT [CK_CONFIAPI_IND_EIXO_ORIGEM_ME] CHECK ([IND_NOTA_ORIGEM_ME] IN ('C'))
)
GO

CREATE INDEX [IDX_CONFIAPI_001] ON [W3IN].[CONFIGURACAO_API] 
(
	[COD_MODULO] ASC
)
GO

CREATE INDEX [IDX_CONFIAPI_002] ON [W3IN].[CONFIGURACAO_API] 
(
	[COD_REGRA_VER_AVALIACAO] ASC
)
GO