CREATE TABLE [W3IN].[MODELO_CONFIGURACAO_API] (
  [COD_API]				  INT NOT NULL,
	[COD_MODULO]			INT NOT NULL,
	[COD_MODELO]			INT NOT NULL,
	CONSTRAINT [PK_MOCONAPI] PRIMARY KEY CLUSTERED ([COD_API] ASC, [COD_MODULO] ASC, [COD_MODELO] ASC),
	CONSTRAINT [FK_MOCONAPI_MODULO] FOREIGN KEY ([COD_MODULO]) 
		REFERENCES [W3SI].[MODULO] ([COD_MODULO]) ON DELETE CASCADE,
  )
	GO

	CREATE INDEX [IDX_MOCONAPI_001] ON [W3IN].[MODELO_CONFIGURACAO_API] 
	(
		[COD_MODULO] ASC
	)
	GO

	CREATE INDEX [IDX_MOCONAPI_002] ON [W3IN].[MODELO_CONFIGURACAO_API] 
	(
		[COD_MODELO] ASC
	)
	GO