CREATE TABLE [W3IN].[TIPO_INTEGRACAO]
(
	[COD_TIPO_INTEGRACAO] INT NOT NULL, 
    [NOM_TIPO_INTEGRACAO] VARCHAR(255) NOT NULL,

	CONSTRAINT PK_TIPOINTE PRIMARY KEY CLUSTERED ([COD_TIPO_INTEGRACAO] ASC)
)
