<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="atencao">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
  <Mensagem chave="erro">
    <pt-BR><![CDATA[Atenção!]]></pt-BR>
    <en-US><![CDATA[Attention!]]></en-US>
    <es-ES><![CDATA[Atención!]]></es-ES>
  </Mensagem>
  <Mensagem chave="aguarde_carregando">
    <pt-BR><![CDATA[Aguarde carregando...]]></pt-BR>
    <en-US><![CDATA[Loading...Please Wait...]]></en-US>
    <es-ES><![CDATA[Espere…Cargando…]]></es-ES>
  </Mensagem>
	<Mensagem chave="campo_preenchimento_obrigatorio">
		<pt-BR><![CDATA[Campo de preenchimento obrigatório]]></pt-BR>
		<en-US><![CDATA[Mandatory completion field ]]></en-US>
		<es-ES><![CDATA[Campo de cumplimentación obligatoria]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_autenticacao_sa3">
		<pt-BR><![CDATA[Informe a URL de integração com o Portal de Autoatendimento: (Ex.: {UrlBase}/api.autoatendimento/token)]]></pt-BR>
		<en-US><![CDATA[Enter the integration URL with the Self-Service Portal: (Ex.: {UrlBase}/api.autoatendimento/token)]]></en-US>
		<es-ES><![CDATA[Ingrese la URL de integración con el Portal de Autoservicio: (Ej.: {UrlBase}/api.autoatendimento/token)]]></es-ES>
	</Mensagem>
  <Mensagem chave="dados_salvos_com_sucesso">
    <pt-BR><![CDATA[Dados salvos com sucesso!]]></pt-BR>
    <en-US><![CDATA[Data saved successfully!]]></en-US>
    <es-ES><![CDATA[¡Datos guardados con éxito!]]></es-ES>
  </Mensagem>
  <Mensagem chave="url_invalida">
    <pt-BR><![CDATA[Informe um endereço válido]]></pt-BR>
    <en-US><![CDATA[Please provide a valid address]]></en-US>
    <es-ES><![CDATA[Proporcione una dirección válida]]></es-ES>
  </Mensagem>
</Mensagens>
