<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="portal_autoatendimento">
		<pt-BR>Portal de Autoatendimento</pt-BR>
		<en-US>Self-Service Portal</en-US>
		<es-ES>Portal de Autoservicio</es-ES>
	</Mensagem>
	<Mensagem chave="gente_treinamento">
		<pt-BR>Gen.te Aprende Treinamento</pt-BR>
		<en-US>Gen.te Learn Training</en-US>
		<es-ES>Gen.te Aprender Capacitacion</es-ES>
	</Mensagem>
	<Mensagem chave="fit_comportamento_clave">
		<pt-BR>Fit de Comportamentos Clave</pt-BR>
		<en-US>Clave Behavior Fit</en-US>
		<es-ES>Fit de comportamiento clave</es-ES>
	</Mensagem>
	<Mensagem chave="configracoes_de_apis">
		<pt-BR>Configurações de APIs</pt-BR>
		<en-US>API settings</en-US>
		<es-ES>Configuración de la API</es-ES>
	</Mensagem>
	<Mensagem chave="configuracao_integracao">
		<pt-BR>Configurações de integração</pt-BR>
		<en-US>Integration Settings</en-US>
		<es-ES>Configuración de integración</es-ES>
	</Mensagem>
	<Mensagem chave="workflow_de_movimentacao_e_rescicao">
		<pt-BR>Workflow de Movimentação e Rescisão</pt-BR>
		<en-US>Movement and Termination Workflow</en-US>
		<es-ES>Flujo de trabajo de movimiento y terminación</es-ES>
	</Mensagem>
	<Mensagem chave="configuracao">
		<pt-BR>Configuração</pt-BR>
		<en-US>Setting</en-US>
		<es-ES>Configuración</es-ES>
	</Mensagem>
	<Mensagem chave="autenticacao_integrada">
		<pt-BR>Autenticação integrada</pt-BR>
		<en-US>Integrated authentication</en-US>
		<es-ES>Autenticación integrada</es-ES>
	</Mensagem>
	<Mensagem chave="dados_corporativos">
		<pt-BR>Dados corporativos</pt-BR>
		<en-US>Corporate data</en-US>
		<es-ES>Datos corporativos</es-ES>
	</Mensagem>
	<Mensagem chave="erro">
		<pt-BR>Erro</pt-BR>
		<en-US>Error</en-US>
		<es-ES>Erro</es-ES>
	</Mensagem>
	<Mensagem chave="atencao">
		<pt-BR>Atenção!</pt-BR>
		<en-US>Caution!</en-US>
		<es-ES>¡Atencion!</es-ES>
	</Mensagem>
	<Mensagem chave="modulos">
		<pt-BR>Módulos</pt-BR>
		<en-US>Módulos</en-US>
		<es-ES>Módulos</es-ES>
	</Mensagem>
	<Mensagem chave="competencias">
		<pt-BR>Competências</pt-BR>
		<en-US>Competence</en-US>
		<es-ES>Competencias</es-ES>
	</Mensagem>
</Mensagens>
