<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
  <Mensagem chave="configuracao">
    <pt-BR>Configurações</pt-BR>
    <en-US>Configurations</en-US>
    <es-ES>Configuraciones</es-ES>
  </Mensagem>
  <Mensagem chave="erro">
	  <pt-BR>Atenção!</pt-BR>
	  <en-US>Warning!</en-US>
    <es-ES>¡Atención!</es-ES>
  </Mensagem>
	<Mensagem chave="configuracoesCiclo">
		<pt-BR>Configurações do Ciclo</pt-BR>
		<en-US>Cycle Configurations</en-US>
		<es-ES>Configuraciones del ciclo</es-ES>
	</Mensagem>
	<Mensagem chave="configuracoesGerais">
		<pt-BR>Configurações Gerais</pt-BR>
		<en-US>General Settings</en-US>
		<es-ES>Configuraciones Generales</es-ES>
	</Mensagem>
	<Mensagem chave="integracoes">
		<pt-BR>Integrações</pt-BR>
		<en-US>Integrations</en-US>
		<es-ES>Integraciones</es-ES>
	</Mensagem>
  <Mensagem chave="configuracoes_cliente">
    <pt-BR>Configurações do Cliente</pt-BR>
    <en-US>Client configurations</en-US>
    <es-ES>Configuraciones del Cliente</es-ES>
  </Mensagem>
</Mensagens>
