-- VERIFICAÇÃO DA VERSÃO ATUAL DO BANCO DE DADOS
SET NOEXEC OFF

IF W3IN.FN_VERSAO_IN() <> '2023.3.0' BEGIN
	PRINT 'Versão atual: ' + W3IN.FN_VERSAO_IN()
	RAISERROR('ERRO: Estas alterações são incompatíveis com a versão atual.', 18, 1) WITH NOWAIT
	SET NOEXEC ON
END
GO

-- ARMAZENA AS CONFIGURAÇÕES REFERENTES A APIs do UTILIZADAS NO INTEGRADOR
IF NOT EXISTS (
	SELECT 1
	FROM SYS.TABLES T
	WHERE SCHEMA_NAME(T.SCHEMA_ID) = 'W3IN'
	AND T.NAME = 'CONFIGURACAO_API')
BEGIN
	CREATE TABLE [W3IN].[CONFIGURACAO_API] (
		[COD_API]						INT NOT NULL,
    [COD_MODULO]					INT NOT NULL,
		[COD_REGRA_VER_AVALIACAO]		INT NULL,
		[IND_TIPO_VALIDACAO_AC]			CHAR(1) NULL,
		[IND_NOTA_ORIGEM_AC]			CHAR(1) NULL,
		[IND_NOTA_ORIGEM_RC]			CHAR(1) NULL,
		[IND_NOTA_ORIGEM_ME]			CHAR(1) NULL,		
		[IND_EXPIRACAO_RESULTADOS]		CHAR(1) NOT NULL
			CONSTRAINT [DF_CONFIAPI_IND_EXPIRACAO_RESULTADOS]
				DEFAULT 'N'
            CONSTRAINT [CK_CONFIAPI_IND_EXPIRACAO_RESULTADOS]
                CHECK ([IND_EXPIRACAO_RESULTADOS] IN ('S', 'N')),
		[IND_ANO_REFERENCIA]			CHAR(1) NOT NULL
			CONSTRAINT [DF_CONFIAPI_IND_ANO_REFERENCIA]
				DEFAULT 'N'
            CONSTRAINT [CK_CONFIAPI_IND_ANO_REFERENCIA]
                CHECK ([IND_ANO_REFERENCIA] IN ('S', 'N')),
		[IND_RANGE_ESPECIFICO]			CHAR(1) NOT NULL
			CONSTRAINT [DF_CONFIAPI_IND_RANGE_ESPECIFICO]
				DEFAULT 'N'
            CONSTRAINT [CK_CONFIAPI_IND_RANGE_ESPECIFICO]
                CHECK ([IND_RANGE_ESPECIFICO] IN ('S', 'N')),
		[QTD_DIAS_EXPIRACAO]			INT NULL,
		[NUM_ANO_REFERENCIA]			INT NULL,
		[VLR_MINIMO_RANGE]				FLOAT NULL,
		[VLR_MAXIMO_RANGE]				FLOAT NULL,
        CONSTRAINT [PK_CONFIAPI] PRIMARY KEY CLUSTERED ([COD_API] ASC, [COD_MODULO] ASC),
		CONSTRAINT [FK_CONFIAPI_MODULO] FOREIGN KEY ([COD_MODULO]) 
			REFERENCES [W3SI].[MODULO] ([COD_MODULO]) ON DELETE CASCADE,
		CONSTRAINT [CK_CONFIAPI_IND_TIPO_VALIDACAO_AC] CHECK ([IND_TIPO_VALIDACAO_AC] IN ('C', 'V', 'R')),
		CONSTRAINT [CK_CONFIAPI_IND_EIXO_ORIGEM_AC] CHECK ([IND_NOTA_ORIGEM_AC] IN ('X', 'Y', 'Z')),
		CONSTRAINT [CK_CONFIAPI_IND_EIXO_ORIGEM_RC] CHECK ([IND_NOTA_ORIGEM_RC] IN ('X', 'Y')),
		CONSTRAINT [CK_CONFIAPI_IND_EIXO_ORIGEM_ME] CHECK ([IND_NOTA_ORIGEM_ME] IN ('C'))
    )

	CREATE INDEX [IDX_CONFIAPI_001] ON [W3IN].[CONFIGURACAO_API] 
	(
		[COD_MODULO] ASC
	)

	CREATE INDEX [IDX_CONFIAPI_002] ON [W3IN].[CONFIGURACAO_API] 
	(
		[COD_REGRA_VER_AVALIACAO] ASC
	)
END
GO

-- ARMAZENA MODELOS DE COMPETÊNCIAS VINCULADOS A DETERMIDADA REGRA DE API
IF NOT EXISTS (
	SELECT 1
	FROM SYS.TABLES T
	WHERE SCHEMA_NAME(T.SCHEMA_ID) = 'W3IN'
	AND T.NAME = 'MODELO_CONFIGURACAO_API')
BEGIN
	CREATE TABLE [W3IN].[MODELO_CONFIGURACAO_API] (
        [COD_API]				INT NOT NULL,
		[COD_MODULO]			INT NOT NULL,
		[COD_MODELO]			INT NOT NULL,
		CONSTRAINT [PK_MOCONAPI] PRIMARY KEY CLUSTERED ([COD_API] ASC, [COD_MODULO] ASC, [COD_MODELO] ASC),
		CONSTRAINT [FK_MOCONAPI_MODULO] FOREIGN KEY ([COD_MODULO]) 
			REFERENCES [W3SI].[MODULO] ([COD_MODULO]) ON DELETE CASCADE,
    )

	CREATE INDEX [IDX_MOCONAPI_001] ON [W3IN].[MODELO_CONFIGURACAO_API] 
	(
		[COD_MODULO] ASC
	)

	CREATE INDEX [IDX_MOCONAPI_002] ON [W3IN].[MODELO_CONFIGURACAO_API] 
	(
		[COD_MODELO] ASC
	)
END
GO