-- VERIFICAÇÃO DA VERSÃO ATUAL DO BANCO DE DADOS
SET NOEXEC OFF

IF W3IN.FN_VERSAO_IN() <> '2023.3.0' BEGIN
	PRINT 'Versão atual: ' + W3IN.FN_VERSAO_IN()
	RAISERROR('ERRO: Estas alterações são incompatíveis com a versão atual.', 18, 1) WITH NOWAIT
	SET NOEXEC ON
END
GO


IF EXISTS (SELECT 1
					FROM SYSOBJECTS
					WHERE  ID = OBJECT_ID('W3IN.FN_CALCULAR_MEDIA_RELATIVA')
					AND TYPE IN ('FN')) BEGIN
   DROP FUNCTION W3IN.FN_CALCULAR_MEDIA_RELATIVA
END
GO

CREATE FUNCTION W3IN.FN_CALCULAR_MEDIA_RELATIVA (@VLR_NOTA FLOAT, @MIN_NOTA FLOAT, @MAX_NOTA FLOAT, @MIN_RELATIVO FLOAT, @MAX_RELATIVO FLOAT)
	RETURNS DECIMAL(10, 2)
AS  
BEGIN
	DECLARE @VLR_RELATIVO FLOAT
	
	IF @MAX_NOTA = @MIN_NOTA
		SET @VLR_RELATIVO = @MAX_NOTA
	ELSE
		SET @VLR_RELATIVO = @MIN_RELATIVO + (((@VLR_NOTA - @MIN_NOTA) * (@MAX_RELATIVO - @MIN_RELATIVO)) / (@MAX_NOTA - @MIN_NOTA))

	RETURN CONVERT(DECIMAL(10, 2), @VLR_RELATIVO)
END
GO

IF EXISTS(SELECT OBJECT_ID FROM SYS.OBJECTS WHERE NAME = 'FN_VERSAO_IN' AND TYPE = 'FN')
	DROP FUNCTION  W3IN.FN_VERSAO_IN;
GO

CREATE FUNCTION W3IN.FN_VERSAO_IN()
RETURNS VARCHAR(20)
BEGIN
	RETURN '2023.4.0'
END