<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="competencias">
		<pt-BR>Competências</pt-BR>
		<en-US>Competence</en-US>
		<es-ES>Competencias</es-ES>
	</Mensagem>	
	<Mensagem chave="titulo">
		<pt-BR><![CDATA[Selecione os ciclos avaliativos que retornarão informações para os widgets do Portal de Autoatendimento:]]></pt-BR>
		<en-US><![CDATA[Select the evaluative cycles that will return information to the widgets of Self-Service Portal:]]></en-US>
		<es-ES><![CDATA[Seleccione los ciclos de evaluación que devolverán información a los widgets del Portal de Autoservicio:]]></es-ES>
	</Mensagem>	
	<Mensagem chave="coluna_ciclo">
		<pt-BR><![CDATA[Ciclo]]></pt-BR>
		<en-US><![CDATA[Cycle]]></en-US>
		<es-ES><![CDATA[Ciclo]]></es-ES>
	</Mensagem>	
	<Mensagem chave="coluna_data_inicio">
		<pt-BR><![CDATA[Data de Início]]></pt-BR>
		<en-US><![CDATA[Start Date]]></en-US>
		<es-ES><![CDATA[Fecha de Inicio]]></es-ES>
	</Mensagem>
	<Mensagem chave="coluna_data_fim">
		<pt-BR><![CDATA[Data Fim]]></pt-BR>
		<en-US><![CDATA[End Date]]></en-US>
		<es-ES><![CDATA[Fecha Final]]></es-ES>
	</Mensagem>
	<Mensagem chave="nao_ha_ciclos">
		<pt-BR><![CDATA[Não existem ciclos cadastrados]]></pt-BR>
		<en-US><![CDATA[There are no cycles registered]]></en-US>
		<es-ES><![CDATA[No hay ciclos inscritos]]></es-ES>
	</Mensagem>
	<Mensagem chave="dados_salvos_com_sucesso">
		<pt-BR><![CDATA[Dados salvos com sucesso!]]></pt-BR>
		<en-US><![CDATA[Data saved successfully!]]></en-US>
		<es-ES><![CDATA[¡Datos guardados con éxito!]]></es-ES>
	</Mensagem>
	<Mensagem chave="erro">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="aguarde_carregando">
		<pt-BR><![CDATA[Aguarde carregando...]]></pt-BR>
		<en-US><![CDATA[Loading...Please Wait...]]></en-US>
		<es-ES><![CDATA[Espere…Cargando…]]></es-ES>
	</Mensagem>
</Mensagens>
