<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
  <Mensagem chave="nomeModulo">
    <pt-BR>Integrador - Administração</pt-BR>
    <en-US>Integrator - Administration</en-US>
    <es-ES>Integrador - Administración</es-ES>
  </Mensagem>
  <Mensagem chave="link">
    <pt-BR>Caso a janela não abra automaticamente, clique aqui.</pt-BR>
    <en-US>In case the window does not open automatically, click here.</en-US>
    <es-ES>Si la ventana no se abre automáticamente, haga clic aquí.</es-ES>
  </Mensagem>
	<Mensagem chave="integracoes">
		<pt-BR>Integrações</pt-BR>
		<en-US>Integrations</en-US>
		<es-ES>Integraciones</es-ES>
	</Mensagem>
</Mensagens>
