<?xml version="1.0" encoding="utf-8"?>
<Mensagens>
  <Mensagem chave="retornar">
    <pt-BR><![CDATA[Retornar upload]]></pt-BR>
    <en-US><![CDATA[Return upload]]></en-US>
    <es-ES><![CDATA[Volver upload]]></es-ES>
  </Mensagem>
  <Mensagem chave="importar">
    <pt-BR><![CDATA[Confirmar importação]]></pt-BR>
    <en-US><![CDATA[Confirm import]]></en-US>
    <es-ES><![CDATA[Confirme importación]]></es-ES>
  </Mensagem>
  <Mensagem chave="cancelar">
    <pt-BR><![CDATA[Cancelar]]></pt-BR>
    <en-US><![CDATA[Cancel]]></en-US>
    <es-ES><![CDATA[Cancelar]]></es-ES>
  </Mensagem>
  <Mensagem chave="exportar">
    <pt-BR><![CDATA[Exportar grid]]></pt-BR>
    <en-US><![CDATA[Export grid]]></en-US>
    <es-ES><![CDATA[Exportar rejilla]]></es-ES>
  </Mensagem>
</Mensagens>