<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="nota_ciclo_origem_eixo_x_competencias">
		<pt-BR><![CDATA[Nota do Eixo X]]></pt-BR>
		<en-US><![CDATA[Axis Note X]]></en-US>
		<es-ES><![CDATA[Nota del eje X]]></es-ES>
	</Mensagem>
	<Mensagem chave="nota_ciclo_origem_eixo_y_competencias">
		<pt-BR><![CDATA[Nota do Eixo Y]]></pt-BR>
		<en-US><![CDATA[Axis Note Y]]></en-US>
		<es-ES><![CDATA[Nota del eje Y]]></es-ES>
	</Mensagem>
	<Mensagem chave="nota_ciclo_origem_eixo_z_competencias">
		<pt-BR><![CDATA[Nota do Eixo Z]]></pt-BR>
		<en-US><![CDATA[Axis Note Z]]></en-US>
		<es-ES><![CDATA[Nota del eje Z]]></es-ES>
	</Mensagem>
	<Mensagem chave="nota_ciclo_origem_eixo_x_calibragem">
		<pt-BR><![CDATA[Nota do Eixo X]]></pt-BR>
		<en-US><![CDATA[Axis Note X]]></en-US>
		<es-ES><![CDATA[Nota del eje X]]></es-ES>
	</Mensagem>
	<Mensagem chave="nota_ciclo_origem_eixo_y_calibragem">
		<pt-BR><![CDATA[Nota do Eixo Y]]></pt-BR>
		<en-US><![CDATA[Axis Note Y]]></en-US>
		<es-ES><![CDATA[Nota del eje Y]]></es-ES>
	</Mensagem>
	<Mensagem chave="configuracao_adicionais">
		<pt-BR><![CDATA[Configurações Adicionais]]></pt-BR>
		<en-US><![CDATA[Additional Settings]]></en-US>
		<es-ES><![CDATA[Ajustes adicionales]]></es-ES>
	</Mensagem>
	<Mensagem chave="desconsiderar_resultados_que_tenham_sido_gerados_a_mais_de">
		<pt-BR><![CDATA[Desconsiderar resultados que tenham sido gerados à mais de]]></pt-BR>
		<en-US><![CDATA[Disregard results that have been generated more than]]></en-US>
		<es-ES><![CDATA[Ignorar los resultados que se han generado más de]]></es-ES>
	</Mensagem>
	<Mensagem chave="limitar_resultados_ao_ano_de_referencia">
		<pt-BR><![CDATA[Limitar resultados ao ano de referência]]></pt-BR>
		<en-US><![CDATA[Limit results to the reference year]]></en-US>
		<es-ES><![CDATA[Limitar los resultados al año de referencia]]></es-ES>
	</Mensagem>
	<Mensagem chave="converter_os_resultados_para_o_range">
		<pt-BR><![CDATA[Converter os resultados para o range]]></pt-BR>
		<en-US><![CDATA[Convert results to range]]></en-US>
		<es-ES><![CDATA[Conversor de resultados para rango]]></es-ES>
	</Mensagem>
	<Mensagem chave="dias">
		<pt-BR><![CDATA[dias.]]></pt-BR>
		<en-US><![CDATA[days.]]></en-US>
		<es-ES><![CDATA[dias.]]></es-ES>
	</Mensagem>
	<Mensagem chave="competencias">
		<pt-BR><![CDATA[Competências]]></pt-BR>
		<en-US><![CDATA[Skills]]></en-US>
		<es-ES><![CDATA[Habilidades]]></es-ES>
	</Mensagem>
	<Mensagem chave="metas">
		<pt-BR><![CDATA[Metas]]></pt-BR>
		<en-US><![CDATA[Goals]]></en-US>
		<es-ES><![CDATA[Metas]]></es-ES>
	</Mensagem>
	<Mensagem chave="calibragem">
		<pt-BR><![CDATA[Calibragem]]></pt-BR>
		<en-US><![CDATA[Consistency]]></en-US>
		<es-ES><![CDATA[Consistencia]]></es-ES>
	</Mensagem>
	<Mensagem chave="nota_de_origem">
		<pt-BR><![CDATA[Nota de origem]]></pt-BR>
		<en-US><![CDATA[Origin note]]></en-US>
		<es-ES><![CDATA[Nota de origen]]></es-ES>
	</Mensagem>
	<Mensagem chave="resultado_do_ciclo">
		<pt-BR><![CDATA[Resultado do Ciclo]]></pt-BR>
		<en-US><![CDATA[Cycle Result]]></en-US>
		<es-ES><![CDATA[Resultado del ciclo]]></es-ES>
	</Mensagem>
	<Mensagem chave="configuracao_para_definicao_da_nota">
		<pt-BR><![CDATA[Configuração para definição da nota que será enviada na API de retorno do resultado de Desempenho]]></pt-BR>
		<en-US><![CDATA[Configuration for defining the grade that will be sent in the Performance result return API]]></en-US>
		<es-ES><![CDATA[Configuración para definir la calificación que se enviará en la API de devolución de resultados de rendimiento]]></es-ES>
	</Mensagem>
	<Mensagem chave="modelos_de_competencia_considerados">
		<pt-BR><![CDATA[Modelos de competência considerados]]></pt-BR>
		<en-US><![CDATA[Competence models considered]]></en-US>
		<es-ES><![CDATA[Modelos de competencias considerados]]></es-ES>
	</Mensagem>
	<Mensagem chave="regra_para_acesso_ao_resultado">
		<pt-BR><![CDATA[Regra para acesso ao resultado]]></pt-BR>
		<en-US><![CDATA[Rule for accessing the result]]></en-US>
		<es-ES><![CDATA[Regla para acceder al resultado]]></es-ES>
	</Mensagem>
	<Mensagem chave="caso_ja_exista_resultado_consolidado">
		<pt-BR><![CDATA[Caso já exista resultado consolidado]]></pt-BR>
		<en-US><![CDATA[If there is already consolidated result]]></en-US>
		<es-ES><![CDATA[Si ya hay resultado consolidado]]></es-ES>
	</Mensagem>
	<Mensagem chave="regra_do_ver_avaliacao">
		<pt-BR><![CDATA[Regra do Ver Avaliação]]></pt-BR>
		<en-US><![CDATA[View Review Rule]]></en-US>
		<es-ES><![CDATA[Regra do Ver Avaliação]]></es-ES>
	</Mensagem>
	<Mensagem chave="regra_especifica">
		<pt-BR><![CDATA[Regra específica]]></pt-BR>
		<en-US><![CDATA[Specific rule]]></en-US>
		<es-ES><![CDATA[Regla especifica]]></es-ES>
	</Mensagem>
	<Mensagem chave="minimo">
		<pt-BR><![CDATA[Mínimo]]></pt-BR>
		<en-US><![CDATA[Minimum]]></en-US>
		<es-ES><![CDATA[Mínimo]]></es-ES>
	</Mensagem>
	<Mensagem chave="maximo">
		<pt-BR><![CDATA[Máximo]]></pt-BR>
		<en-US><![CDATA[Maximum]]></en-US>
		<es-ES><![CDATA[Máximo]]></es-ES>
	</Mensagem>
	<Mensagem chave="sim">
		<pt-BR><![CDATA[Sim]]></pt-BR>
		<en-US><![CDATA[Yes]]></en-US>
		<es-ES><![CDATA[Si]]></es-ES>
	</Mensagem>
	<Mensagem chave="nao">
		<pt-BR><![CDATA[Não]]></pt-BR>
		<en-US><![CDATA[No]]></en-US>
		<es-ES><![CDATA[No]]></es-ES>
	</Mensagem>
	<Mensagem chave="selecione">
		<pt-BR><![CDATA[Selecione]]></pt-BR>
		<en-US><![CDATA[Select]]></en-US>
		<es-ES><![CDATA[Seleccionar]]></es-ES>
	</Mensagem>
	<Mensagem chave="dados_salvos_com_sucesso">
		<pt-BR><![CDATA[Dados salvos com sucesso!]]></pt-BR>
		<en-US><![CDATA[Data saved successfully!]]></en-US>
		<es-ES><![CDATA[¡Datos guardados con éxito!]]></es-ES>
	</Mensagem>
	<Mensagem chave="o_minimo_do_range_nao_pode_ser_maior_que_o_maximo">
		<pt-BR><![CDATA[O mínimo do range não pode ser maior que o máximo.]]></pt-BR>
		<en-US><![CDATA[The minimum of the range cannot be greater than the maximum.]]></en-US>
		<es-ES><![CDATA[El mínimo del rango no puede ser mayor que el máximo.]]></es-ES>
	</Mensagem>
	<Mensagem chave="campo_preenchimento_obrigatorio">
		<pt-BR><![CDATA[Campo de preenchimento obrigatório]]></pt-BR>
		<en-US><![CDATA[Mandatory completion field ]]></en-US>
		<es-ES><![CDATA[Campo de cumplimentación obligatoria]]></es-ES>
	</Mensagem>
</Mensagens>
