<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="atencao">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="erro">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="aguarde_carregando">
		<pt-BR><![CDATA[Aguarde carregando...]]></pt-BR>
		<en-US><![CDATA[Loading...Please Wait...]]></en-US>
		<es-ES><![CDATA[Espere…Cargando…]]></es-ES>
	</Mensagem>
	<Mensagem chave="campo_preenchimento_obrigatorio">
		<pt-BR><![CDATA[Campo de preenchimento obrigatório]]></pt-BR>
		<en-US><![CDATA[Mandatory completion field ]]></en-US>
		<es-ES><![CDATA[Campo de cumplimentación obligatoria]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_base">
		<pt-BR><![CDATA[URL Base (Ex.: https://login.lg.com.br)]]></pt-BR>
		<en-US><![CDATA[Base URL (Ex.: https://login.lg.com.br)]]></en-US>
		<es-ES><![CDATA[URL Base (Ex.: https://login.lg.com.br)]]></es-ES>
	</Mensagem>
	<Mensagem chave="chave_publica">
		<pt-BR><![CDATA[Chave Pública]]></pt-BR>
		<en-US><![CDATA[Public Key]]></en-US>
		<es-ES><![CDATA[Llave Pública]]></es-ES>
	</Mensagem>
	<Mensagem chave="chave_privada">
		<pt-BR><![CDATA[Chave Privada]]></pt-BR>
		<en-US><![CDATA[Private Key]]></en-US>
		<es-ES><![CDATA[Llave Privada]]></es-ES>
	</Mensagem>
	<Mensagem chave="sim">
		<pt-BR><![CDATA[Sim]]></pt-BR>
		<en-US><![CDATA[Yes]]></en-US>
		<es-ES><![CDATA[Si]]></es-ES>
	</Mensagem>
	<Mensagem chave="nao">
		<pt-BR><![CDATA[Não]]></pt-BR>
		<en-US><![CDATA[Not]]></en-US>
		<es-ES><![CDATA[No]]></es-ES>
	</Mensagem>

	<Mensagem chave="dados_salvos_com_sucesso">
		<pt-BR><![CDATA[Dados salvos com sucesso!]]></pt-BR>
		<en-US><![CDATA[Data saved successfully!]]></en-US>
		<es-ES><![CDATA[¡Datos guardados con éxito!]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_invalida">
		<pt-BR><![CDATA[Informe um endereço válido]]></pt-BR>
		<en-US><![CDATA[Please provide a valid address]]></en-US>
		<es-ES><![CDATA[Proporcione una dirección válida]]></es-ES>
	</Mensagem>
</Mensagens>
