<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
  <Mensagem chave="incluir">
    <pt-BR>Incluir</pt-BR>
    <en-US>Insert</en-US>
    <es-ES>Incluir</es-ES>
  </Mensagem>
  <Mensagem chave="editar">
    <pt-BR>Editar</pt-BR>
    <en-US>Edit</en-US>
    <es-ES>Editar</es-ES>
  </Mensagem>
  <Mensagem chave="clonar">
    <pt-BR>Clonar</pt-BR>
    <en-US>Clone</en-US>
    <es-ES>Clon</es-ES>
  </Mensagem>
  <Mensagem chave="excluir">
    <pt-BR>Excluir</pt-BR>
    <en-US>Delete</en-US>
    <es-ES>Excluir</es-ES>
  </Mensagem>
  <Mensagem chave="moverbaixo">
    <pt-BR>Mover para baixo</pt-BR>
    <en-US>Move down</en-US>
    <es-ES>Mover hacia abajo</es-ES>
  </Mensagem>
  <Mensagem chave="movercima">
    <pt-BR>Mover para cima</pt-BR>
    <en-US>Move up</en-US>
    <es-ES>Subir</es-ES>
  </Mensagem>
  <Mensagem chave="atualizar">
    <pt-BR>Atualizar</pt-BR>
    <en-US>Refresh</en-US>
    <es-ES>Actualización</es-ES>
  </Mensagem>
  <Mensagem chave="trocarseletor">
    <pt-BR>Seletor</pt-BR>
    <en-US>Selector</en-US>
    <es-ES>Selector</es-ES>
  </Mensagem>
  <Mensagem chave="selradio">
    <pt-BR>RadioBox</pt-BR>
    <en-US>RadioBox</en-US>
    <es-ES>RadioBox</es-ES>
  </Mensagem>
  <Mensagem chave="selcheck">
    <pt-BR>CheckBox</pt-BR>
    <en-US>CheckBox</en-US>
    <es-ES>CheckBox</es-ES>
  </Mensagem>
  <Mensagem chave="filtros">
    <pt-BR>Filtros</pt-BR>
    <en-US>Filters</en-US>
    <es-ES>Filtros</es-ES>
  </Mensagem>
  <Mensagem chave="filtrolimpar">
    <pt-BR>Limpar todos os filtros</pt-BR>
    <en-US>Clean all filters</en-US>
    <es-ES>Excluir todos los filtros</es-ES>
  </Mensagem>
  <Mensagem chave="filtroadicional">
    <pt-BR>Filtros adicionais</pt-BR>
    <en-US>Advanced filters</en-US>
    <es-ES>Filtros avanzados</es-ES>
  </Mensagem>
  <Mensagem chave="expimp">
    <pt-BR>Exportar / Importar</pt-BR>
    <en-US>Export / Import</en-US>
    <es-ES>Exportación / Importación</es-ES>
  </Mensagem>
  <Mensagem chave="exportgrid">
    <pt-BR>Exportar Grid</pt-BR>
    <en-US>Export Grid</en-US>
    <es-ES>Exportación de Grid</es-ES>
  </Mensagem>
  <Mensagem chave="exportar">
    <pt-BR>Exportar Dados</pt-BR>
    <en-US>Export Data</en-US>
    <es-ES>Exportación de Datos</es-ES>
  </Mensagem>
  <Mensagem chave="importar">
    <pt-BR>Importar Dados</pt-BR>
    <en-US>Import Data</en-US>
    <es-ES>Importación de Datos</es-ES>
  </Mensagem>
</Mensagens>
