<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
  <Mensagem chave="retornar">
    <pt-BR>Retornar upload</pt-BR>
    <en-US>Return upload</en-US>
    <es-ES>Retorno upload</es-ES>
  </Mensagem>
  <Mensagem chave="importar">
    <pt-BR>Confirmar importação</pt-BR>
    <en-US>Confirm import</en-US>
    <es-ES>Confirmar Importación</es-ES>
  </Mensagem>
  <Mensagem chave="cancelar">
    <pt-BR>Cancelar</pt-BR>
    <en-US>Cancel</en-US>
    <es-ES>Cancelar</es-ES>
  </Mensagem>
  <Mensagem chave="exportar">
    <pt-BR>Exportar grid</pt-BR>
    <en-US>Export grid</en-US>
    <es-ES>Exportación de Grid</es-ES>
  </Mensagem>
</Mensagens>
