<?xml version="1.0" encoding="utf-8" ?>
<Mensagens>
	<Mensagem chave="atencao">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="erro">
		<pt-BR><![CDATA[Atenção!]]></pt-BR>
		<en-US><![CDATA[Attention!]]></en-US>
		<es-ES><![CDATA[Atención!]]></es-ES>
	</Mensagem>
	<Mensagem chave="aguarde_carregando">
		<pt-BR><![CDATA[Aguarde carregando...]]></pt-BR>
		<en-US><![CDATA[Loading...Please Wait...]]></en-US>
		<es-ES><![CDATA[Espere…Cargando…]]></es-ES>
	</Mensagem>
	<Mensagem chave="campo_preenchimento_obrigatorio">
		<pt-BR><![CDATA[Campo de preenchimento obrigatório]]></pt-BR>
		<en-US><![CDATA[Mandatory completion field ]]></en-US>
		<es-ES><![CDATA[Campo de cumplimentación obligatoria]]></es-ES>
	</Mensagem>

	<Mensagem chave="envio_dados_corporativos">
		<pt-BR><![CDATA[Indica se o envio de dados corporativos para o sistema da Clave está habilitado]]></pt-BR>
		<en-US><![CDATA[Indicates whether sending corporate data to the Clave system is enabled]]></en-US>
		<es-ES><![CDATA[Indica si está habilitado el envío de datos corporativos al sistema Clave]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_base_api">
		<pt-BR><![CDATA[Indica a URL base para acesso as API's e ao login SSO, do sistema Fit de Comportamentos Clave]]></pt-BR>
		<en-US><![CDATA[Indicates the base URL for API access and SSO login, of the Fit Clave Behavior system]]></en-US>
		<es-ES><![CDATA[Indica la URL base para el acceso a la API y el inicio de sesión SSO, del sistema Fit Clave Behavior]]></es-ES>
	</Mensagem>
	<Mensagem chave="token_client_secret">
		<pt-BR><![CDATA[Valor da chave fornecido pelo sistema Fit de Comportamentos Clave, para geração do Hash obrigatório nas integrações de autenticação e de APIs]]></pt-BR>
		<en-US><![CDATA[Key value provided by the Fit Clave Behavior system, to generate the mandatory Hash in authentication and API integrations]]></en-US>
		<es-ES><![CDATA[Valor de clave proporcionado por el sistema Fit Clave Behavior, para generar el Hash obligatorio en autenticación e integraciones API]]></es-ES>
	</Mensagem>
	<Mensagem chave="sim">
		<pt-BR><![CDATA[Sim]]></pt-BR>
		<en-US><![CDATA[Yes]]></en-US>
		<es-ES><![CDATA[Si]]></es-ES>
	</Mensagem>
	<Mensagem chave="nao">
		<pt-BR><![CDATA[Não]]></pt-BR>
		<en-US><![CDATA[Not]]></en-US>
		<es-ES><![CDATA[No]]></es-ES>
	</Mensagem>

	<Mensagem chave="dados_salvos_com_sucesso">
		<pt-BR><![CDATA[Dados salvos com sucesso!]]></pt-BR>
		<en-US><![CDATA[Data saved successfully!]]></en-US>
		<es-ES><![CDATA[¡Datos guardados con éxito!]]></es-ES>
	</Mensagem>
	<Mensagem chave="url_invalida">
		<pt-BR><![CDATA[Informe um endereço válido]]></pt-BR>
		<en-US><![CDATA[Please provide a valid address]]></en-US>
		<es-ES><![CDATA[Proporcione una dirección válida]]></es-ES>
	</Mensagem>
</Mensagens>
