-- TIPO DE INTEGRAÇÃO
INSERT INTO W3IN.TIPO_INTEGRACAO (COD_TIPO_INTEGRACAO, NOM_TIPO_INTEGRACAO) VALUES (1, 'Autoatendimento')
INSERT INTO W3IN.TIPO_INTEGRACAO (COD_TIPO_INTEGRACAO, NOM_TIPO_INTEGRACAO) VALUES (2, 'Autenticação Integrada')

-- CONFIGURACAO_INTEGRACAO
-- Autoatendimento
INSERT INTO W3IN.CONFIGURACAO_INTEGRACAO (COD_TIPO_INTEGRACAO, ID_CONFIGURACAO_INTEGRACAO, VLR_CONFIGURACAO_INTEGRACAO, DAT_ALTERACAO) VALUES (1, 'UrlIntegracaoSA3', 'https://login.lg.com.br/api.autoatendimento/token', getdate())
INSERT INTO W3IN.CONFIGURACAO_INTEGRACAO (COD_TIPO_INTEGRACAO, ID_CONFIGURACAO_INTEGRACAO, VLR_CONFIGURACAO_INTEGRACAO, DAT_ALTERACAO) VALUES (1, 'CiclosCompetenciasAutoatendimento', '', getdate())
-- Autenticação Integrada
INSERT INTO W3IN.CONFIGURACAO_INTEGRACAO (COD_TIPO_INTEGRACAO, ID_CONFIGURACAO_INTEGRACAO, VLR_CONFIGURACAO_INTEGRACAO, DAT_ALTERACAO) VALUES (2, 'UrlBase', 'https://login.lg.com.br', getdate())
INSERT INTO W3IN.CONFIGURACAO_INTEGRACAO (COD_TIPO_INTEGRACAO, ID_CONFIGURACAO_INTEGRACAO, VLR_CONFIGURACAO_INTEGRACAO, DAT_ALTERACAO) VALUES (2, 'ChavePublica', 'ec0e957c-c0d7-4284-b557-88ba6610ea1d', getdate())
INSERT INTO W3IN.CONFIGURACAO_INTEGRACAO (COD_TIPO_INTEGRACAO, ID_CONFIGURACAO_INTEGRACAO, VLR_CONFIGURACAO_INTEGRACAO, DAT_ALTERACAO) VALUES (2, 'ChavePrivada', '9bc85c98-9bae-4446-b1d8-4004ebeab5a4', getdate())
GO
