DECLARE 
	@codModulo INT = 30

-- DELETE
DELETE FROM W3SI.PARAMETRO WHERE COD_MODULO = @codModulo
DELETE FROM W3SI.SUBMODULO WHERE COD_MODULO = @codModulo
DELETE FROM W3SI.MODULO WHERE COD_MODULO = @codModulo

-- MODULO
INSERT INTO W3SI.MODULO (COD_MODULO, SGL_MODULO, IND_TIPO_MODULO, NOM_MODULO, NOM_USUARIO_BANCO, DSC_URL) VALUES (@codModulo, 'IN', 'S', 'Integrador', 'W3IN', 'LG.HCM.Integrador/')

-- SUBMODULOS
INSERT INTO W3SI.SUBMODULO VALUES(3001, @codModulo, 'TR', 'M', 'Gen.te Aprende – Treinamento', 'IntegracaoLms.aspx', 'S', 'N', 'N')
INSERT INTO W3SI.SUBMODULO VALUES(3002, @codModulo, 'CL', 'M', 'Fit de Comportamentos Clave ', 'IntegracaoClave.aspx', 'S', 'N', 'N')

-- PARAMETROS
DECLARE 
	@urlSI VARCHAR(4000)

SELECT @urlSI = VLR_PARAMETRO FROM W3SI.PARAMETRO WHERE COD_MODULO IS NULL AND NOM_PARAMETRO ='UrlSI'

SELECT * INTO W3SI.TMP_PARAMETRO FROM W3SI.PARAMETRO WHERE 1 = 2

-- Parametros Integração LMS
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) VALUES ('A', @codModulo, 'S', 'IntegracaoTreinamento.EnvioDadosCorporativos', 'Indica se o envio de dados corporativos para o sistema Gen.te Aprende - Treinamento está habilitado.', 'FALSE', 'TRUE, Sim;FALSE, Não')
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) VALUES ('A', @codModulo, 'S', 'IntegracaoTreinamento.TokenClientId', 'Valor do client_id fornecido pelo sistema Gen.te Aprende - Treinamento, para permitir a autenticaçao Oauth2 nas API''s do sistema.', 'client_id', NULL)
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) VALUES ('A', @codModulo, 'C', 'IntegracaoTreinamento.TokenClientSecret', 'Valor do client_secret fornecido pelo sistema Gen.te Aprende - Treinamento, para permitir a autenticaçao Oauth2 nas API''s do sistema.', 'r0q7qBU2681jrAwuaojKHPDHJ7sLyNUMHBNlU2BKV3M=', NULL)
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) VALUES ('A', @codModulo, 'S', 'IntegracaoTreinamento.UrlBaseApi', 'Indica a URL base para acesso as API''s do sistema Gen.te Aprende - Treinamento.', 'https://localhost/webapi/', NULL, 'N')

-- Parametros Integração Clave
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) VALUES ('A', @codModulo, 'C', 'IntegracaoClave.Chave', 'Indica se o envio de dados corporativos para o sistema da Clave está habilitado.', 'r0q7qBU2681jrAwuaojKHPDHJ7sLyNUMHBNlU2BKV3M=', NULL)
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) VALUES ('A', @codModulo, 'S', 'IntegracaoClave.EnvioDadosCorporativos', 'Indica se o envio de dados corporativos para o sistema da Clave está habilitado.', 'FALSE', 'TRUE, Sim;FALSE, Não')
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) VALUES ('A', @codModulo, 'S', 'IntegracaoClave.UrlBase', 'Indica a URL base para acesso as APIs e ao login SSO, do sistema Fit de Comportamentos', 'https://localhost/webapi/', NULL)

-- Demais parâmetros
INSERT INTO W3SI.TMP_PARAMETRO (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) VALUES ('A', @codModulo, 'S', 'Url', 'URL do Modulo. A URL deve conter a barra "/" no final.', @urlSI + 'Modulos/LG.HCM.Integrador/', NULL)

MERGE W3SI.PARAMETRO AS TARGET
USING W3SI.TMP_PARAMETRO AS SOURCE 
ON (TARGET.COD_MODULO = 30 AND SOURCE.COD_MODULO = 30 AND TARGET.NOM_PARAMETRO = SOURCE.NOM_PARAMETRO)
WHEN MATCHED AND
	TARGET.IND_ESCOPO <> SOURCE.IND_ESCOPO
	OR TARGET.IND_TIPO_VALOR <> SOURCE.IND_TIPO_VALOR
	OR TARGET.NOM_PARAMETRO <> SOURCE.NOM_PARAMETRO
	OR TARGET.DSC_PARAMETRO <> SOURCE.DSC_PARAMETRO
	OR TARGET.DSC_OPCAO <> SOURCE.DSC_OPCAO
THEN 
	UPDATE SET
		TARGET.IND_ESCOPO = SOURCE.IND_ESCOPO,
		TARGET.IND_TIPO_VALOR = SOURCE.IND_TIPO_VALOR,
		TARGET.NOM_PARAMETRO = SOURCE.NOM_PARAMETRO,
		TARGET.DSC_PARAMETRO = SOURCE.DSC_PARAMETRO,
		TARGET.DSC_OPCAO = SOURCE.DSC_OPCAO
WHEN NOT MATCHED BY TARGET THEN
	INSERT (IND_ESCOPO, COD_MODULO, IND_TIPO_VALOR, NOM_PARAMETRO, DSC_PARAMETRO, VLR_PARAMETRO, DSC_OPCAO) 
	VALUES (SOURCE.IND_ESCOPO, SOURCE.COD_MODULO, SOURCE.IND_TIPO_VALOR, SOURCE.NOM_PARAMETRO, SOURCE.DSC_PARAMETRO, SOURCE.VLR_PARAMETRO, SOURCE.DSC_OPCAO);

--VINCULA OS PARAMETROS PARA OS PERFIS
SELECT * INTO W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO FROM W3SI.PERFIL_ADMINISTRADOR_PARAMETRO WHERE 1 = 2

DECLARE 
	@codPerfilAdminLG INT = 1,
	@codPerfilAdminGeral INT = 2,
	@codPerfilAdminAuxiliar INT = 3,
	@codPerfilConsultor INT = 4

--INSERE TODOS OS PARAMETROS PARA O ADMINISTRADOR LG
INSERT INTO W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO (COD_PERFIL_ADMINISTRADOR, COD_PARAMETRO)
	SELECT @codPerfilAdminLG, COD_PARAMETRO 
	FROM W3SI.PARAMETRO P
	WHERE COD_MODULO = @codModulo

--INSERE TODOS OS PARAMETROS PARA O ADMINISTRADOR GERAL
INSERT INTO W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO (COD_PERFIL_ADMINISTRADOR, COD_PARAMETRO)
	SELECT @codPerfilAdminGeral, COD_PARAMETRO 
	FROM W3SI.PARAMETRO P
	WHERE COD_MODULO = @codModulo

--INSERE TODOS OS PARAMETROS PARA O CONSULTOR
INSERT INTO W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO (COD_PERFIL_ADMINISTRADOR, COD_PARAMETRO)
	SELECT @codPerfilConsultor, COD_PARAMETRO 
	FROM W3SI.PARAMETRO P
	WHERE COD_MODULO = @codModulo

--APLICA O MERGE
MERGE W3SI.PERFIL_ADMINISTRADOR_PARAMETRO AS TARGET
USING W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO AS SOURCE 
ON (TARGET.COD_PERFIL_ADMINISTRADOR = SOURCE.COD_PERFIL_ADMINISTRADOR AND TARGET.COD_PARAMETRO = SOURCE.COD_PARAMETRO)
WHEN NOT MATCHED BY TARGET AND SOURCE.COD_PARAMETRO IN (SELECT COD_PARAMETRO FROM W3SI.PARAMETRO WHERE COD_MODULO = @codModulo) THEN
	INSERT (COD_PERFIL_ADMINISTRADOR, COD_PARAMETRO) 
	VALUES (SOURCE.COD_PERFIL_ADMINISTRADOR, SOURCE.COD_PARAMETRO)
WHEN NOT MATCHED BY SOURCE AND TARGET.COD_PARAMETRO IN (SELECT COD_PARAMETRO FROM W3SI.PARAMETRO WHERE COD_MODULO = @codModulo) THEN
DELETE;

DROP TABLE W3SI.TMP_PERFIL_ADMINISTRADOR_PARAMETRO
DROP TABLE W3SI.TMP_PARAMETRO
GO
